adventurerscodex/adventurerscodex

app.js, index.html, notes/app.js, notes/index.html, profile/app.js, profile/index.html, profile/profile.tmpl.html
Needed to move around the jquery document.ready handlers into the individual
HTML page because they were interfering with the main dashboard.
Also removed the clear button from the profile.
=> Created profile.

ability_scores/ability.tmpl.html, ability_scores/app.js, ability_scores/index.html, app.js, index.html
Woot woot, my first pull request for this project.
=> Ability scores new

CONTRIBUTING.md, README.md
- Added more information regarding contributing (package structure and required functions)
- Added more info to the realm.
Oh, and I failed at branch naming...
=> Updated docs

CONTRIBUTING.md, README.md, app.js, index.html, site.css
I've added the health section of the stats module. Temporary hit points are supported!
=> Added Stats Module

Web.config, backpack/app.js, backpack/backpack.css, backpack/backpack.tmpl.html, backpack/index.html, profile/profile.tmpl.html
Backpack module mostly complete.
=> Backpack 5

ability_scores/app.js
=> Add clear, import and export functions

.gitignore, ability_scores/app.js, app.js, bin/knockout-file-bind.js, bower.json, index.html, profile/profile.tmpl.html, site.css
Had to touch @jkrooskos's code though :)
=> Added global import/export/clear functionality.

stats/stats.tmpl.html
=> Added label to stats bar.

.editorconfig
This way we're all in sync with style.
=> Added Editor config for all.

LICENSE
After we reviewed the licenses, we chose the GPL v2 License.
=> Added license 

bower.json, mocha.html, test/test_notes.js, test/test_profile.js, test/test_stats.js
To test this branch:
- Once you've cloned the repo, bower install the dependencies. There's a new one.
- Open `mocha.html` in a browser. You should see all the tests run.
=> Added Unittesting with Mocha! Finally!

.gitignore, CONTRIBUTING.md, Gruntfile.js, README.md, bower.json, karma.conf.js, mocha.html, package.json, test/test_notes.js, test/test_profile.js, test/test_stats.js
Using Karma, Grunt, and Istanbul we noe have test coverage measurements!
To use these features you'll need to run `npm install` from the project root directory.
I've updated the documentation to account for this change.
=> Added test coverage

.travis.yml, package.json
This is the minimum required to get the project to build on Travis. I didn't include a badge because I'm not sure which account you want the builds to run under.
=> Added Travis configuration, and changes to install bower stuff automatically

app.js, index.html, mocha.html, site.css, spell-slots/app.js, spell-slots/index.html, spell-slots/spell-slots.tmpl.html, test/test_spell_slots.js
I had to redo the PR since some of the page broke due to an optimization I tried to make. The tests didn't catch the error unfortunately.
All should be good now.
Fixed issue #31
=> Added spell slots module (for real this time)

app.js, index.html, karma.conf.js, mocha.html, package.json, skills/app.js, skills/index.html, skills/skills.tmpl.html, test/test_skills.js, test/test_spell_slots.js
Need to `npm install` after merging.
=> Added skills module

spell_slots/spell_slots.tmpl.html
=> Fixes confusing spell slots design.

app.js, appearance/app.js, appearance/appearance.tmpl.html, index.html, models/appearance.js, profile/app.js, profile/profile.tmpl.html, test/test_appearance.js
=> Added appearance module.

equipment/app.js, equipment/equipment.tmpl.html, equipped_items/app.js, equipped_items/equipped_items.tmpl.html
=> Added quick equip buttons

ability_scores/ability.tmpl.html, ability_scores/app.js, mocha.html, test/test_ability_scores.js
Added:
Changes to style
Change bindings type
Computed observables for modifiers
Added tests
=> Ability scores

ability_scores/ability.tmpl.html, ability_scores/app.js, test/test_ability_scores.js
=> Ability scores 159

app.js, index.html
Changes the initilization order on page load to speed up first time visitor
redirection. By putting the check at the top of the page, it will execute before any bindings are applied or template files are downloaded.
=> Speeds up page load.

equipment/equipment.tmpl.html, equipped_items/equipped_items.tmpl.html, skills/skills.tmpl.html, spell_slots/spell_slots.tmpl.html, spells/spells.tmpl.html
Sorting now obeys the default sort type.
=> Fixes sort onload binding.

characters/index.html, index.html, models/health.js, models/hit_dice.js, models/other_stats.js, stats/app.js, stats/stats.tmpl.html
This is two issues. Added AC, Speed, Initiative, inspiration, and hit dice.
=> Add to stats 66

characters/index.html, chat/chat.tmpl.html, connection_manager/connection_manager.tmpl.html, docs/notes.txt, index.html
Some modules still need to be improved, but the glaring issues are fixed.
=> Fixes mobile UI layout issues.

sheet/index.html, sheet/spell_slots/spell_slots.tmpl.html
=> Changes the look of the spell slots module.

charactersheet/charactersheet/app.js, charactersheet/charactersheet/index.html
=> Hides page until bindings are applied.

charactersheet/charactersheet/models/spell.js, charactersheet/charactersheet/spells/spells.tmpl.html
=> Fixed issue 227 and 228

charactersheet/charactersheet/models/health.js
Made a couple changes. Added validation so that NaN doesn't come up on the HP calculation. The progress bar was also not changing because of the NaN, so I added a small validation in regularHitpointsRemaining calculation
=> Fixed HP bug

deploy.sh, package.json
=> Adds deployment script.

charactersheet/charactersheet/models/skill.js
Changed Skill's code to match the saving throw's code in the proficiency calculation.
=> Proficiency Checkmark

charactersheet/charactersheet/models/saving_throws.js, charactersheet/charactersheet/models/skill.js, charactersheet/charactersheet/skills/app.js, charactersheet/charactersheet/skills/skills.tmpl.html
Changed Ability Scores in Skills from text input to button group select. Also, added a delete function to Skills and Saving throws because they didn't have one.
=> Changed Ability Scores in Skills modal

charactersheet/charactersheet/skills/skills.tmpl.html
Changed Ability Scores in Skills from text input to button group select. Also, added a delete function to Skills and Saving throws because they didn't have one.
=> Aligned width of input groups and button group

charactersheet/charactersheet/ability_scores/ability.tmpl.html, charactersheet/charactersheet/appearance/appearance.tmpl.html, charactersheet/charactersheet/campaign/campaign.tmpl.html, charactersheet/charactersheet/connection_manager/connection_manager.tmpl.html, charactersheet/charactersheet/enemies/enemies.tmpl.html, charactersheet/charactersheet/equipment/equipment.css, charactersheet/charactersheet/equipment/equipment.tmpl.html, charactersheet/charactersheet/feats_prof/feats_prof.tmpl.html, charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/players.js, charactersheet/charactersheet/notes/notes.tmpl.html, charactersheet/charactersheet/profile/profile.tmpl.html, charactersheet/charactersheet/saving_throws/saving_throws.tmpl.html, charactersheet/charactersheet/skills/app.js, charactersheet/charactersheet/spell_slots/app.js, charactersheet/charactersheet/spell_slots/spell_slots.tmpl.html, charactersheet/charactersheet/spell_stats/spell_stats.tmpl.html, charactersheet/charactersheet/spells/app.js, charactersheet/charactersheet/spells/spells.tmpl.html, charactersheet/charactersheet/stats/stats.tmpl.html
Did a find all to find all the comments. Then went though, manually, to each section to make sure it can be removed.
=> Code cleanup

charactersheet/charactersheet/ability_scores/app.js
Added a check for empty string in ability score calculation. Got rid of nulls.
=> Fix null calculation on Ability Scores

charactersheet/charactersheet/models/saving_throws.js, charactersheet/charactersheet/saving_throws/saving_throws.tmpl.html
The "bonus" calculation was incorrect. It would parse the variable and then overwrite it at the end. Therefore causing the legit, usable value to be rendered un-used and completely ignored. Changed it so that the value could be retained.
=> Fixed calculation is saving_throw model.

charactersheet/charactersheet/models/spell.js
Changed _Attack_ to _Attack Roll_ in spells
=> Changed Attack to Attack Roll in spells

.gitignore, charactersheet/charactersheet/app.js, charactersheet/charactersheet/armor/app.js, charactersheet/charactersheet/armor/armors.tmpl.html, charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/armor.js, charactersheet/charactersheet/models/weapon.js, charactersheet/charactersheet/saving_throws/saving_throws.tmpl.html, charactersheet/charactersheet/skills/skills.tmpl.html, charactersheet/charactersheet/weapons/app.js, charactersheet/charactersheet/weapons/weapons.tmpl.html
Added two new tables, complete with models and controllers, for weapons and armors. I added the fields that I think would be relevant. The layout and fields included/displayed are up for debate, though.
=> Weapons and Armors

.gitignore, bower.json, charactersheet/bin/knockout_boostrap_select_bind.js, charactersheet/characters/index.html, charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/hit_dice.js, charactersheet/charactersheet/models/hit_dice_type.js, charactersheet/charactersheet/models/spell.js, charactersheet/charactersheet/stats/app.js, charactersheet/charactersheet/stats/stats.tmpl.html
Added select for the user to choose their type of hit dice for their class. The location of the select is up for debate. I just thought it'd logically go here.
=> Added hit dice type to Stats

charactersheet/charactersheet/stats/app.js
This is what i get for doing PRs before bed.
=> Fix for accidental merge with experiemental branch.

charactersheet/charactersheet/app.js, charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/player_types.js
Sorted modules into tabs according to #267.
Tried to make layout within tabs as visually appealing as possible, but it's open for discussion.
I also tried to keep mobile devices in mind.
=> Character sheet layout now in tabs

charactersheet/charactersheet/models/character.js, charactersheet/charactersheet/templates/wizard.tmpl.html, charactersheet/charactersheet/viewmodels/characters.js, charactersheet/charactersheet/viewmodels/root.js, charactersheet/charactersheet/viewmodels/wizard.js
=> Reimplements import.

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/armor.js, charactersheet/charactersheet/templates/armors.tmpl.html, charactersheet/charactersheet/templates/stats.tmpl.html, charactersheet/charactersheet/viewmodels/armor.js
=> Removed obsolete column 'Armor Bonus'

charactersheet/charactersheet/models/chat_message.js, charactersheet/charactersheet/models/player_info.js, charactersheet/charactersheet/models/player_summary.js, charactersheet/charactersheet/templates/chat.tmpl.html, charactersheet/charactersheet/templates/connection_manager.tmpl.html, charactersheet/charactersheet/viewmodels/chat.js, charactersheet/charactersheet/viewmodels/player_image.js
- Fixes #328, and #376 
- Also fixes an issue that would cause new gravatar settings to not be applied.
- Gravatar images also now default to 'mystery man' when not found.
=> Adds profile pic to chat.

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/death_save.js, charactersheet/charactersheet/models/hit_dice.js, charactersheet/charactersheet/templates/stats.tmpl.html, charactersheet/charactersheet/viewmodels/stats.js
Added death saves to stats module per #312.
=> Death saves 312

charactersheet/charactersheet/viewmodels/stats.js
=> Fixed logic in death saves

charactersheet/charactersheet/models/spell.js
=> added a special option for spell range

bower.json, charactersheet/charactersheet/models/other_stats.js, charactersheet/charactersheet/models/skill.js, charactersheet/charactersheet/templates/stats.tmpl.html, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/skills.js, charactersheet/charactersheet/viewmodels/stats.js, karma.conf.js, test/mocks/mock_character_manager.js, test/mocks/mock_persistence_service.js, test/models/test_item.js, test/models/test_other_stats.js
The styling leaves something to be desired, but we should work on this more with #382
=> Adds passive wisdom field.

test/fixtures.js, test/mocks/nav.html, test/models/test_npc.js, test/models/test_profile.js, test/services/test_players.js, test/viewmodels/test_chat.js, test/viewmodels/test_player_summary_viewmodel.js, test/viewmodels/test_skills.js
=> Adds more tests

charactersheet/charactersheet/viewmodels/spells.js
=> Add boolean sort to spells module

charactersheet/charactersheet/templates/armors.tmpl.html, charactersheet/charactersheet/templates/spells.tmpl.html, charactersheet/charactersheet/templates/weapons.tmpl.html
=> Add select2 to the rest of the options bindings

charactersheet/charactersheet/models/saving_throws.js, charactersheet/charactersheet/viewmodels/armor.js, charactersheet/charactersheet/viewmodels/saving_throws.js, charactersheet/charactersheet/viewmodels/skills.js
=> Add boolean sort to proficiency columns in remaining modules

CHANGELOG.md
=> Update changelog for release 3

charactersheet/charactersheet/templates/stats.tmpl.html, charactersheet/charactersheet/viewmodels/root.js, charactersheet/charactersheet/viewmodels/stats.js
Fixed the hit dice type issue. #411 
Fixed the character switching issue. 
Fixed saving throw issue.
=> Various fixes

charactersheet/charactersheet/templates/stats.tmpl.html
Changed layout as directed by #382.
Fixed #382.
=> Changed the layout of the stats module

charactersheet/charactersheet/models/armor.js, charactersheet/charactersheet/models/item.js, charactersheet/charactersheet/models/weapon.js, charactersheet/charactersheet/templates/armors.tmpl.html, charactersheet/charactersheet/templates/items.tmpl.html, charactersheet/charactersheet/templates/weapons.tmpl.html, charactersheet/charactersheet/viewmodels/armor.js, charactersheet/charactersheet/viewmodels/items.js, charactersheet/charactersheet/viewmodels/weapons.js
Added a select2 drop down for the "item cost" fields in the following modules:
- Armor
- Weapon
- Inventory
They look much like this:
Fixed #355
=> Currency denomination #355

charactersheet/charactersheet/models/spell.js, charactersheet/charactersheet/templates/spells.tmpl.html
=> Add spell save attr to model and view

charactersheet/charactersheet/templates/skills.tmpl.html
=> Fix modifier sort in skills module

charactersheet/charactersheet/templates/stats.tmpl.html
=> Change labels for death saves and proficiency

charactersheet/charactersheet/templates/feats_prof.tmpl.html
=> Change proficiency label to Proficiencies and Languages

charactersheet/charactersheet/index.html, charactersheet/charactersheet/services/sort_service.js, charactersheet/charactersheet/viewmodels/armor.js, charactersheet/charactersheet/viewmodels/items.js, charactersheet/charactersheet/viewmodels/saving_throws.js, charactersheet/charactersheet/viewmodels/skills.js, charactersheet/charactersheet/viewmodels/spell_slots.js, charactersheet/charactersheet/viewmodels/spells.js, charactersheet/charactersheet/viewmodels/weapons.js
=> Adds new sort service

charactersheet/charactersheet/templates/spell_stats.tmpl.html
=> Add select2 tagging for Spell Casting Ability

charactersheet/charactersheet/index.html, charactersheet/charactersheet/templates/wizard.tmpl.html
=> Fixes issue where view wasnt scrollable after import

charactersheet/charactersheet/models/saving_throws.js
=> Display +0 in savings throw bonus if attribute is null

charactersheet/charactersheet/templates/feat_traits.tmpl.html, charactersheet/charactersheet/templates/feats_prof.tmpl.html, charactersheet/charactersheet/templates/notes.tmpl.html, charactersheet/charactersheet/templates/treasure.tmpl.html, charactersheet/site.css
=> Add dark-area class to textareas

charactersheet/charactersheet/models/health.js, charactersheet/charactersheet/templates/stats.tmpl.html, charactersheet/site.css
=> Fixes progress label

charactersheet/charactersheet/models/weapon.js, charactersheet/charactersheet/templates/weapons.tmpl.html, charactersheet/charactersheet/viewmodels/weapons.js
uses prof, stats, and magical mod
=> Weapon hit 380

charactersheet/charactersheet/models/hit_dice.js, charactersheet/charactersheet/viewmodels/stats.js
=> fixes hit dice persistence issue and usage save issue

charactersheet/charactersheet/models/skill.js
=> fixes skill modifier not being shown when 0

charactersheet/charactersheet/viewmodels/player_summary.js, test/viewmodels/test_player_summary_viewmodel.js
=> Add unload of player summary subscription

charactersheet/charactersheet/viewmodels/stats.js
Now correctly unsubscribes items from subscription. 
Fixes #417
=> Added clean up of viewmodel

charactersheet/charactersheet/models/armor.js, charactersheet/charactersheet/templates/armors.tmpl.html, charactersheet/charactersheet/viewmodels/armor.js
Added _UNUSED_ armor calculations.
* Removed armor penalty and changed it to armor stealth.
* Changed dex bonus to armor class
Fixes #436
=> Changed what data is captured for the armor

charactersheet/charactersheet/services/sort_service.js
Fixes #465
- Feature was accidentally removed during addition of sort service.
=> Fixes boolean sorting.

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/magic_item.js, charactersheet/charactersheet/templates/magic_items.tmpl.html, charactersheet/charactersheet/viewmodels/magic_items.js, charactersheet/charactersheet/viewmodels/root.js, mocha.html, test/fixtures.js, test/models/test_armor.js, test/models/test_magic_item.js, test/viewmodels/test_magic_items.js
=> Magic items 437

charactersheet/charactersheet/index.html
=> Fix magic item alignment issue

charactersheet/charactersheet/models/hit_dice.js, charactersheet/site.css
Fixed height issue on hit dice where image would get cut off.
=> Hit Dice Height issue

charactersheet/charactersheet/templates/spells.tmpl.html
=> Only show prepared spells if the spell is not a cantrip

charactersheet/charactersheet/models/weapon.js, charactersheet/charactersheet/services/sort_service.js, charactersheet/charactersheet/templates/weapons.tmpl.html, charactersheet/charactersheet/viewmodels/weapons.js, test/fixtures.js, test/utilities/test_sort_service.js
=> Fixes Descending Sort 

charactersheet/charactersheet/models/character.js, charactersheet/charactersheet/models/player_summary.js, charactersheet/charactersheet/models/spell.js, charactersheet/charactersheet/models/spell_stats.js, test/models/test_character.js, test/models/test_chat_message.js, test/models/test_connection_manager.js, test/models/test_death_save.js, test/models/test_feats_traits.js, test/models/test_hit_dice.js, test/models/test_hit_dice_type.js, test/models/test_player_summary.js, test/models/test_spell.js, test/models/test_spell_stats.js
=> Added various tests and had to change some models to be testable.

charactersheet/charactersheet/utilities/fixtures.js
=> adds spell duration 8 hours

test/characters/Jebeddo Nimblewit.json, test/characters/Thoros Arroway.json
=> Add test characters

bower.json, charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/armor.js, charactersheet/charactersheet/models/saving_throws.js, charactersheet/charactersheet/models/skill.js, charactersheet/charactersheet/templates/armors.tmpl.html, charactersheet/charactersheet/templates/items.tmpl.html, charactersheet/charactersheet/templates/magic_items.tmpl.html, charactersheet/charactersheet/templates/saving_throws.tmpl.html, charactersheet/charactersheet/templates/skills.tmpl.html, charactersheet/charactersheet/templates/spell_slots.tmpl.html, charactersheet/charactersheet/templates/spells.tmpl.html, charactersheet/charactersheet/templates/weapons.tmpl.html, charactersheet/site.css, test/models/test_armor.js, test/models/test_saving_throws.js, test/models/test_skill.js
=> Add font-awesome, and change checkmark, add, and remove icons

charactersheet/charactersheet/templates/feats_prof.tmpl.html
=> Change text area name to Features

charactersheet/charactersheet/templates/spell_slots.tmpl.html
=> Add refresh icon to spell slots and delete reset btn

test/viewmodels/test_weapons.js
=> Add tests for weapons view model

charactersheet/charactersheet/templates/saving_throws.tmpl.html
Add hover over color red to remove icons
Fixes #583
None
**Desired Reviewer:** @{username}
@Sonictherocketman 
@tanyxp
=> Add hover over color red to remove icons

charactersheet/charactersheet/models/daily_feature.js, charactersheet/charactersheet/templates/daily_features.tmpl.html, charactersheet/charactersheet/viewmodels/daily_features.js, charactersheet/site.css
Added the same color bar that spell slots has. Also, added the "edit" property to the "max" column. 
Fixes #582 
N/A
**Desired Reviewer:** 
@Sonictherocketman 
@jkrooskos
=> Added color bar to daily features.

charactersheet/charactersheet/models/daily_feature.js, charactersheet/charactersheet/templates/daily_features.tmpl.html, charactersheet/charactersheet/templates/spell_slots.tmpl.html, charactersheet/charactersheet/viewmodels/daily_features.js, charactersheet/charactersheet/viewmodels/spell_slots.js, charactersheet/site.css
Changed UI to look like daily features.
Fixes #537 
N/A
Big screen:
Small screen:
**Desired Reviewer:** 
@Sonictherocketman 
@jkrooskos
=> Changed UI to look like daily features.

charactersheet/charactersheet/index.html, charactersheet/charactersheet/init.js, charactersheet/charactersheet/models/character.js, charactersheet/charactersheet/viewmodels/wizard.js
Added dropbox link to app for users to import their character from their dropbox
#606
**Desired Reviewer:** @Sonictherocketman @jkrooskos
=> Dropbox test

.github/ISSUE_TEMPLATE
- Adds new section for a detailed list of tasks to complete. This feature uses GitHub's new checkbox syntax.
**Desired Reviewer:** @tanyxp @jkrooskos
=> Adds checkbox steps to issue template.

CONTRIBUTING.md, docs/getting_started.md
Updates contributing information and adds a new getting started page with more detailed information.
Also removes old, incorrect information
Fixes #395 
None
None
**Desired Reviewer:** @jkrooskos @tanyxp
=> Updates Contributing Documentation

test/viewmodels/test_profile.js
Added tests to profile vm
Fixes #639 
N/A
N/A
**Desired Reviewer:** @Sonictherocketman @jkrooskos
=> added tests to profile vm

test/viewmodels/test_player_info.js
Added tests to player info
Fixes #637
**Desired Reviewer:** @Sonictherocketman @jkrooskos
=> Added tests to player info

Gruntfile.js, test/models/test_feat_traits.js, test/viewmodels/test_feat_traits.js, test/viewmodels/test_notes.js
Added tests to Feats VM
Fixes #635 
N/A
N/A
**Desired Reviewer:** @Sonictherocketman  @jkrooskos
=> Added tests to feat traits vm

charactersheet/charactersheet/index.html
Removed missing file from index.html
404 error when fetching models/player_summary.js
This PR closes #662 
**Desired Reviewer:** @{username}
Removed missing file models/player_summary.js from index.html.
=> Remove missing file from index.html

charactersheet/charactersheet/templates/ability.tmpl.html, charactersheet/site.css
Changed how ability scores look
Fixes #655 
**Desired Reviewer:** @Sonictherocketman @jkrooskos
=> Ability scores revamp

charactersheet/charactersheet/index.html, charactersheet/charactersheet/templates/saving_throws.tmpl.html, charactersheet/charactersheet/templates/skills.tmpl.html, charactersheet/charactersheet/templates/spells.tmpl.html
Changes static tables, and spells according to  RFC 653
Fixes #653 
None
=> Fixes according to RFC 653

charactersheet/charactersheet/models/character.js
Fix for export not working post-DM-tools removal
None logged
None
None
=> Fix for exporting characters with old DM data.

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/weapon.js, charactersheet/charactersheet/templates/actions_toolbar.tmpl.html, charactersheet/site.css
Adds Section Descriptions
None logged
None
=> Adds Section Descriptions

charactersheet/charactersheet/models/weapon.js, test/models/test_weapon.js
Fixed wrong labels in weapon hit.
Fixes #670
N/A
=> Fix weapon hit labels

charactersheet/charactersheet/models/armor.js, charactersheet/charactersheet/models/hit_dice_type.js, charactersheet/charactersheet/models/spell.js, charactersheet/charactersheet/models/spell_stats.js, charactersheet/charactersheet/models/weapon.js, test/characters/jebeddo_data.js
Removed static lists from being exported from certain models.
Fixed #676
Less exported data.
=> Reduced exported data

charactersheet/charactersheet/index.html
Adds analytics to the site.
Fixes #681 
None
None
=> Adds Google Analytics

charactersheet/charactersheet/models/character.js, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/ability_scores.js, charactersheet/charactersheet/viewmodels/appearance.js, charactersheet/charactersheet/viewmodels/armor.js, charactersheet/charactersheet/viewmodels/daily_features.js, charactersheet/charactersheet/viewmodels/feat_traits.js, charactersheet/charactersheet/viewmodels/feats_prof.js, charactersheet/charactersheet/viewmodels/items.js, charactersheet/charactersheet/viewmodels/magic_items.js, charactersheet/charactersheet/viewmodels/notes.js, charactersheet/charactersheet/viewmodels/player_image.js, charactersheet/charactersheet/viewmodels/player_info.js, charactersheet/charactersheet/viewmodels/profile.js, charactersheet/charactersheet/viewmodels/saving_throws.js, charactersheet/charactersheet/viewmodels/skills.js, charactersheet/charactersheet/viewmodels/spell_slots.js, charactersheet/charactersheet/viewmodels/spell_stats.js, charactersheet/charactersheet/viewmodels/spells.js, charactersheet/charactersheet/viewmodels/stats.js, charactersheet/charactersheet/viewmodels/treasure.js, charactersheet/charactersheet/viewmodels/weapons.js
- Adds global save event to Notifications.
- All relevant view models subscribe to this event and save their data
- Adds a dispatch for this event when a user clicks the export button.
Fixes #470 
None
None
=> Adds save event and dispatches it when a character is about to be exported

test/characters/jebeddo_data.js
Updates the testing fixture with a more updated data set. 
- This includes a value for magical modifier. Adding a test as according to #719 
- Removes `__id` fields from old test data.
- Adds more detailed testing data (for Daily Features, etc)
Finishes testing #719 
None
None
=> Updates the test fixture with an updated data set.

charactersheet/charactersheet/models/daily_feature.js, charactersheet/charactersheet/viewmodels/daily_features.js
Removed randomness from daily feature colors.
Fixes #660
@Sonictherocketman @jkrooskos
=> Daily feature colors

charactersheet/charactersheet/index.html
Changed verbage
Fixes #730 
@Sonictherocketman @jkrooskos
=> Changed verbage in captions

test/viewmodels/test_actions_toolbar.js
Adds tests for Actions Toolbar.
Fixes #690 
None
None
=> Adds tests for Actions Toolbar

charactersheet/charactersheet/templates/ability.tmpl.html, charactersheet/site.css
Changed modal to small size and change input type to number to support increment and decrement.
Fixes #726
=> Fix width and add number type to input

specs/version_feature_forcast.md
Extracted the details of issue #641 into it's own features document for easier reference.
Fixes #641 
Once a given proposal for a feature has been accepted, it should be formally written into a document and added to the specs directory. 
None
@jkrooskos @tanyxp Thoughts?
=> Adds version forcast document.

charactersheet/charactersheet/index.html, charactersheet/site.css
Adds new Header font.
None logged
None
=> Adds new Header font.

charactersheet/index.html, deploy.sh
Removed conditional redirect and changed CNAME to be app.adventurerscodex.com
Fixes #686
=> Changes for making blog the root.

README.md
Badges for travis were broken after repo reorganization (see #686)
=> Fixes badges

charactersheet/charactersheet/templates/weapons.tmpl.html, charactersheet/charactersheet/viewmodels/weapons.js
Added column for weapon quantity
Fixes #741
=> Added quantity field to weapons table

README.md
Removes redundant information.
Fixed #717
=> Updates Readme by referring to Getting Started

charactersheet/charactersheet/models/spell.js
Fixed a reference to a null element
Fixes #754
=> Fixed spell issue

charactersheet/charactersheet/templates/wizard_profile_step.tmpl.html
- Fixes spelling
- Models have remained the same for legacy reasons.
Fixes #770 
None
=> Fixes misspelt Deity field.

charactersheet/charactersheet/templates/other_stats.tmpl.html
=> Correct passive wisdom to its proper name

charactersheet/charactersheet/templates/wizard_intro_step.tmpl.html
=> Fix incorrect reference/name to get started button

charactersheet/charactersheet/models/other_stats.js, charactersheet/charactersheet/templates/other_stats.tmpl.html, charactersheet/charactersheet/viewmodels/stats.js
Added label for auto-calculating the proficiency score.
Fixes #763
=> Added calculated proficiency bonus

charactersheet/charactersheet/templates/saving_throws.tmpl.html
=> Removes confusing  modifier label from table.

bower.json, charactersheet/bin/knockout-jquery-autocomplete.js, charactersheet/charactersheet/index.html, charactersheet/charactersheet/templates/spells.tmpl.html, charactersheet/site.css
- Adds an Autocomplete binding (to be used for pre-population).
- Documentation in binding docstring.
- None logged, but precursor to #6
=> Adds jQuery Autocomplete binding.

charactersheet/charactersheet/init.js, charactersheet/charactersheet/services/persistence_service.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/utilities/fixtures.js, test/fixtures.js, test/services/test_persistence_service.js
- Adds Migration Engine to allow for data model migrations.
- Adds tests to persistence service and to new migration engine.
Documentation for new migration features are found in the wiki.
Fixes #532
=> Adds Migration Engine

charactersheet/charactersheet/models/saving_throws.js, charactersheet/charactersheet/models/skill.js, charactersheet/charactersheet/models/weapon.js, test/models/test_saving_throws.js, test/models/test_skill.js, test/models/test_weapon.js
Fixed where weapons, savings throw, and skills were getting their proficiency score.
Fixes #794 
Can anyone think of any area I missed? @adventurerscodex/core-developers
=> Calculated Proficiency

charactersheet/charactersheet/templates/wizard_profile_step.tmpl.html, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/viewmodels/wizard_steps/wizard_profile_step.js, package.json, test/viewmodels/test_wizard_profile.js
Race and class now auto-complete on the Wizard Profile screen.
Fixes #769 
Race:
Classes:
The above list is not the full list. It is only what populates when you type corresponding character. The full list can be viewed on the fixtures file.
**Note** 
Changes were made to the package.json.
```
npm install
```
should be run for everyone to make sure that everyone's packages are up to date.
=> Auto complete race & class

charactersheet/bin/knockout-bootstrap-modal.js, charactersheet/charactersheet/index.html, charactersheet/charactersheet/templates/ability.tmpl.html, charactersheet/charactersheet/templates/skills.tmpl.html, charactersheet/charactersheet/viewmodels/ability_scores.js, charactersheet/charactersheet/viewmodels/skills.js
Bootstrap modals can now be triggered programatically. Some examples included.
Tangentially Fixes #230
=> Adds KO Binding For Modals

charactersheet/charactersheet/index.html, charactersheet/charactersheet/templates/wizard_ability_scores_step.tmpl.html, charactersheet/charactersheet/viewmodels/wizard.js, charactersheet/charactersheet/viewmodels/wizard_steps/wizard_ability_scores_step.js, test/viewmodels/test_wizard.js
Adds new step to wizard.
- All fields are required to move on.
None logged. Exists in Feature Forecast.
None
=> Adds new wizard step for ability scores.

charactersheet/charactersheet/templates/treasure.tmpl.html
Lower min to 0 on coin number elements
#820
=> Lower min to 0 on coin number elements

charactersheet/charactersheet/models/character.js, charactersheet/charactersheet/services/persistence_service.js
- Adds a process to import characters from a past version of the app and migrate it forward, then import the data to the app's data store.
None logged.
=> Adds fix for migrations during import process.

charactersheet/charactersheet/models/character.js, test/characters/jebeddo_data.js, test/models/test_character.js, test/services/test_persistence_service.js
=> Fixes linting.

charactersheet/charactersheet/components/proficiency-marker.js, charactersheet/charactersheet/index.html, charactersheet/charactersheet/migrations/110_1_skills.js, charactersheet/charactersheet/models/skill.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/templates/skills.tmpl.html, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/viewmodels/skills.js, charactersheet/site.css, test/characters/jebeddo_data.js, test/fixtures.js, test/migrations/test_migration_110_1_skills.js, test/models/test_skill.js, test/services/test_persistence_service.js
Adds a new set of markers for half and expert proficiency.
Fixes #765
=> Adds New Proficiency Field Markers

charactersheet/charactersheet/templates/skills.tmpl.html
=> Remove modifier header from table

package.json
Test were failing due to incomplete updating of dependencies, this was revered to be revisited at a later time.
None logged
=> Reverts Phantom Dependency

charactersheet/charactersheet/index.html, charactersheet/charactersheet/migrations/110_3_stats.js, charactersheet/charactersheet/services/persistence_service.js, charactersheet/charactersheet/utilities/fixtures.js, test/fixtures.js, test/migrations/test_migration_110_3_stats.js
=> Migration: Stats proficiency

charactersheet/charactersheet/templates/spell_stats.tmpl.html, charactersheet/charactersheet/viewmodels/spell_stats.js
Fixed issue with spell casting ability
=> Fixed spell casting option issue.

charactersheet/charactersheet/models/skill.js, charactersheet/charactersheet/viewmodels/skills.js, test/models/test_skill.js
Fixed logic in skills for determining proficiency bonus. Fixed tests. Skills mod now updates on level update.
Fixes #854
=> Fixed skills not updating

charactersheet/charactersheet/init.js, charactersheet/charactersheet/settings.js
=> Remade PR after Merge was Erased #1

charactersheet/charactersheet/models/spell_slot.js, charactersheet/charactersheet/templates/spell_slots.tmpl.html, charactersheet/charactersheet/viewmodels/spell_slots.js, test/viewmodels/test_spell_slots.js
changes the behavior of the spell slot progress bar to reflect the number of spell slots per spell level
…mber of spell slots per spell level
=> Spell slots

charactersheet/charactersheet/models/armor.js, charactersheet/charactersheet/models/spell.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/templates/armors.tmpl.html, charactersheet/charactersheet/templates/spells.tmpl.html, charactersheet/charactersheet/viewmodels/armor.js, test/models/test_spell.js
- Adds autocomplete to armors.
Fixes #853 
None
None
=> Adds autocomplete to Armors

charactersheet/charactersheet/index.html, charactersheet/charactersheet/migrations/120_1_weapons.js, charactersheet/charactersheet/models/weapon.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/templates/weapons.tmpl.html, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/viewmodels/weapons.js, test/characters/jebeddo_data.js, test/fixtures.js, test/migrations/test_migration_120_1_weapons.js
- Adds autocomplete to the weapons add modal.
- Adds migration from old 'Light' weaponhandedness to ''
- Adds tests
- Adds new fixture data in accordance with the issue #833 
Fixes #833 
None
None
=> Adds Autocomplete to Weapons

charactersheet/charactersheet/templates/actions_toolbar.tmpl.html, charactersheet/site.css
Makes icons more responsive and reduces the button size.
=> Fixes action bar icon size

charactersheet/bin/knockout-bootstrap-modal.js, charactersheet/charactersheet/templates/ability.tmpl.html, charactersheet/charactersheet/templates/armors.tmpl.html, charactersheet/charactersheet/templates/items.tmpl.html, charactersheet/charactersheet/templates/magic_items.tmpl.html, charactersheet/charactersheet/templates/skills.tmpl.html, charactersheet/charactersheet/templates/spells.tmpl.html, charactersheet/charactersheet/templates/weapons.tmpl.html
Extended functionality of modal binding. Now allows for functions to be passed in to be executed on open or close.
Fixes #849
=> Modal open/close function

karma.conf.js
- File saver would cause errors when testing. 
- Removed Filesaver from loaded modules during testing.
None logged.
None
None.
=> Fixes filesaver error when testing.

charactersheet/charactersheet/templates/character/profile.tmpl.html
Fixed deity typo and removed duplicate alignment field.
Fixes #897
=> Removed duplicate alignment

charactersheet/charactersheet/templates/character/index.tmpl.html, charactersheet/charactersheet/templates/character/profile.tmpl.html, charactersheet/site.css
Adds subtitle to tab
#901
Please put feedback below. I took a simple stab at this.
=> Added tab subtitle

charactersheet/charactersheet/models/common/spell.js, charactersheet/charactersheet/templates/character/spells.tmpl.html, charactersheet/charactersheet/viewmodels/character/spells.js
I took a shot at making some edit/preview modal cards for the spells. It only appears in the view/edit modal. Let me know what you all think. It's a really easy fix for us, plus it looks a lot better than the stupid inputs.
Fixes #882 
None
=> Adds preview/edit tabs to spell view/edit modal.

charactersheet/charactersheet/templates/character/index.tmpl.html
Change spell slot title text
Fixes #885
=> Change spell slot title text

charactersheet/charactersheet/templates/character/weapons.tmpl.html
Change range placeholder to more accurate value
Fixes #914
=> Change range placeholder to more accurate value

charactersheet/charactersheet/templates/character/items.tmpl.html
Remove delete button and change placeholder text
Changed title of edit modal to match spells for consistency
Fixes #913
=> Remove delete button and change placeholder text

charactersheet/charactersheet/templates/character/weapons.tmpl.html
=> Change modal title

charactersheet/charactersheet/templates/character/spells.tmpl.html, charactersheet/site.css
Add overflow for spell cards
Fixes #917
=> Add overflow for spell cards

charactersheet/charactersheet/index.html
Fixed text in modal.
Fixes #903
=> Update 'new' modal text

charactersheet/charactersheet/templates/character/index.tmpl.html, charactersheet/charactersheet/templates/character/spell_stats.tmpl.html, charactersheet/charactersheet/viewmodels/character/spells_tab.js, charactersheet/charactersheet/viewmodels/character/stats_tab.js
Move spell stats from stats to spells tab.
Fixes #889 
Large:
Medium:
Small:
Extra-small:
=> Move spell stats to spells

charactersheet/charactersheet/models/common/magic_item.js, charactersheet/charactersheet/templates/character/magic_items.tmpl.html, charactersheet/charactersheet/viewmodels/character/magic_items.js, test/models/test_magic_item.js, test/viewmodels/test_magic_items.js
Add preview tab to magic items
Fixes #909
=> Add preview tab to magic items

charactersheet/charactersheet/models/common/magic_item.js, charactersheet/charactersheet/models/common/spell.js, test/models/test_magic_item.js, test/models/test_spell.js
Add message to previews with empty descriptions
Fixes #949
=> Add message to previews with empty descriptions

charactersheet/charactersheet/models/common/item.js, charactersheet/charactersheet/templates/character/items.tmpl.html, charactersheet/charactersheet/viewmodels/character/items.js, test/models/test_item.js, test/viewmodels/test_items.js
Add items preview tab
Fixes #931
=> Add items preview tab

charactersheet/charactersheet/models/common/armor.js, charactersheet/charactersheet/templates/character/armors.tmpl.html, charactersheet/charactersheet/viewmodels/character/armor.js, test/models/test_armor.js, test/viewmodels/test_armor.js
Add armor preview tab
Fixes #933
=> Add armor preview tab

charactersheet/charactersheet/models/common/weapon.js, charactersheet/charactersheet/templates/character/weapons.tmpl.html, charactersheet/charactersheet/viewmodels/character/weapons.js, test/models/test_weapon.js, test/viewmodels/test_weapons.js
Add weapons preview in edit modal
Fixes #932
=> Add weapons preview in edit modal

README.md, charactersheet/charactersheet/templates/common/wizard_intro_step.tmpl.html, charactersheet/charactersheet/templates/common/wizard_player_type_step.tmpl.html, package.json
Remove ducks in a row reference.
Fixes #959
=> Remove ducks in a row reference.

charactersheet/charactersheet/templates/character/stats.tmpl.html
Fixes an issue where damage would not calculate property if a character had temp-hp
Fixes #963 
None
None
=> Fixes max value with temp HP

charactersheet/charactersheet/models/common/armor.js, charactersheet/charactersheet/templates/character/armors.tmpl.html, test/characters/jebeddo_data.js, test/models/test_armor.js
Add and test armor magical modifier
Fixes #944
=> Add and test armor magical modifier

charactersheet/charactersheet/index.html
Somehow we never caught the fact that the "beta" tag was still at the top of the page...
None logged.
None
=> Removes beta indicator.

charactersheet/charactersheet/models/common/armor.js, charactersheet/charactersheet/templates/character/armors.tmpl.html, charactersheet/charactersheet/viewmodels/character/armor.js, test/characters/jebeddo_data.js, test/models/test_armor.js, test/viewmodels/test_armor.js
Remove proficiency from armor module
Fixes #952
=> Remove proficiency from armor module

charactersheet/charactersheet/templates/character/stats.tmpl.html
Changed temp hp color bar to ```progress-bar-sky```
Fixes #968
=> Changed temp hp color bar

charactersheet/charactersheet/templates/character/ability.tmpl.html, charactersheet/charactersheet/templates/character/armors.tmpl.html, charactersheet/charactersheet/templates/character/daily_features.tmpl.html, charactersheet/charactersheet/templates/character/items.tmpl.html, charactersheet/charactersheet/templates/character/magic_items.tmpl.html, charactersheet/charactersheet/templates/character/saving_throws.tmpl.html, charactersheet/charactersheet/templates/character/spell_slots.tmpl.html, charactersheet/charactersheet/templates/character/spells.tmpl.html, charactersheet/charactersheet/templates/character/stats.tmpl.html, charactersheet/charactersheet/templates/character/weapons.tmpl.html
Updated modal headers per the related issue. Also fixed an issue with editing a weapon.
Fixes #951
=> Updated modal header text

charactersheet/bin/knockout-required-extender.js, charactersheet/charactersheet/index.html, charactersheet/charactersheet/templates/common/wizard_ability_scores_step.tmpl.html, charactersheet/charactersheet/templates/common/wizard_campaign_step.tmpl.html, charactersheet/charactersheet/templates/common/wizard_profile_step.tmpl.html, charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_ability_scores_step.js, charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_campaign_step.js, charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_profile_step.js, charactersheet/site.css
Added __required__ validation extender. Various other similar extenders can be built similar to this one. See the extender for more information on usage.
Fixes #929
=> Validation

charactersheet/charactersheet/templates/character/armors.tmpl.html
Remove unused sort code in armor module
Fixes #983
=> Remove unused sort code in armor module

charactersheet/charactersheet/templates/character/profile.tmpl.html, charactersheet/charactersheet/templates/common/wizard_profile_step.tmpl.html, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/viewmodels/character/profile.js, charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_profile_step.js
Add pre-pop for alignment for wizard and app profile
Fixes #891
=> Add pre-pop for alignment for wizard and app profile

charactersheet/charactersheet/models/character/health.js
Replaces confusing code with simple equivalent.
To whomever is reviewing this, please test that the logic is sound.
Fixes #967
=> Simplify HP logic

charactersheet/charactersheet/templates/character/daily_features.tmpl.html, charactersheet/charactersheet/templates/character/index.tmpl.html
Change name of skills tracking widget (formerly daily features)
Fixes #921
=> Change name of skills tracking widget (formerly daily features)

charactersheet/charactersheet/models/common/treasure.js, charactersheet/charactersheet/templates/character/treasure.tmpl.html, charactersheet/charactersheet/viewmodels/character/treasure.js, test/characters/jebeddo_data.js, test/fixtures.js, test/models/test_treasure.js, test/viewmodels/test_treasure.js
Treasure: Add total weight, test, convert import, export, clear to new conventions
Fixes #985
=> Treasure: Add total weight

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/dm/encounter_sections/notes_section.js, charactersheet/charactersheet/templates/dm/encounter_detail.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/notes_section.tmpl.html, charactersheet/charactersheet/viewmodels/dm/encounter.js, charactersheet/charactersheet/viewmodels/dm/encounter_detail.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/combat_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/notes_section.js, test/models/dm/test_notes_section.js, test/viewmodels/dm/test_encounter.js, test/viewmodels/dm/test_encounter_detail.js, test/viewmodels/dm/test_encounter_tabs.js, test/viewmodels/dm/test_notes_section.js
Adds a model, template, and view model for the NotesSection. This section will house section specific notes for the DM. The view model and model are fully tested and work according to new model and view model standards. New sections should be built with these same goals in mind.
=> Adds the notes section

charactersheet/charactersheet/models/common/weapon.js, charactersheet/charactersheet/templates/character/weapons.tmpl.html, test/models/test_weapon.js
Add calculated range label and test.
Fixes #957
=> Weapons: Add calculated range label and test.

charactersheet/charactersheet/templates/character/profile.tmpl.html, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/viewmodels/character/profile.js
Add background pre-population
Fixes #989
=> Add background pre-population

charactersheet/charactersheet/components/markdown-edit-preview.js, charactersheet/charactersheet/models/common/note.js, charactersheet/charactersheet/templates/character/notes.tmpl.html, charactersheet/charactersheet/viewmodels/character/notes.js, test/viewmodels/test_notes.js
- Notes are now displayed as a selectable list. By default every user has 1
note, and can add more.
- Note titles are auto calculated from their first line and first 25
characters. This makes it super easy for users to add notes and get to work.
- In the case that no note text exists, the title "Empty Note" is
displayed.
- Also cleaned up some miswritten divs in the markdown component.
Fixes #22 (an oldie, but a goodie)
None
=> Adds new functionality for multiple notes.

charactersheet/charactersheet/templates/character/profile.tmpl.html, charactersheet/charactersheet/templates/common/wizard_profile_step.tmpl.html, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/viewmodels/character/profile.js, charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_profile_step.js, test/viewmodels/test_wizard_profile.js
Add race and class pre-pop to profile
Fixes #988
=> Add race and class pre-pop to profile

charactersheet/charactersheet/utilities/view_model_utilities.js
View Model Utilities now provide a more detailed error message.
None logged.
None
None
=> Adds more detailed error message.

README.md, charactersheet/charactersheet/templates/common/wizard_intro_step.tmpl.html, charactersheet/charactersheet/templates/common/wizard_player_type_step.tmpl.html, package.json
Changed Tagline from D&D to RPGs
Fixes #1005
=> Changed Tagline from D&D to RPGs

charactersheet/charactersheet/models/character/profile.js, charactersheet/charactersheet/templates/character/profile.tmpl.html, charactersheet/charactersheet/viewmodels/character/profile.js, test/characters/Jebeddo Nimblewit.json, test/characters/Thoros Arroway.json, test/characters/jebeddo_data.js
Remove religion from app
Fixes #1000
=> Remove religion from app

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/dm/encounter_sections/point_of_interest.js, charactersheet/charactersheet/models/dm/encounter_sections/point_of_interest_section.js, charactersheet/charactersheet/templates/dm/encounter_detail.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/notes_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/point_of_interest.tmpl.html, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/dm/encounter.js, charactersheet/charactersheet/viewmodels/dm/encounter_detail.js, charactersheet/charactersheet/viewmodels/dm/encounter_section_visibility.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/notes_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section.js
- Updates Notes encounter section to use new section methods.
- Solidifies section templates.
- Encounter sections need to subscribe to the `Encounter.changed` notification
to know when their detail view model is changed and needs to update.
- Points of Interest need to have the markdown binding applied and the tabs
None Logged
- Encounter sections need to subscribe to the `Encounter.changed` notification
to know when their detail view model is changed and needs to update.
=> Adds Point of Interest Encounter Section

charactersheet/charactersheet/templates/character/treasure.tmpl.html
Change total gold label
Fixes #1015
=> Change total gold label

charactersheet/charactersheet/models/character/spell_stats.js, charactersheet/charactersheet/templates/character/index.tmpl.html, charactersheet/charactersheet/templates/character/spell_stats.tmpl.html, charactersheet/charactersheet/viewmodels/character/spell_stats.js, test/characters/jebeddo_data.js
Add spell stats table
Fixes #930
=> Add spell stats table

charactersheet/charactersheet/models/character/profile.js, charactersheet/charactersheet/templates/character/profile.tmpl.html, charactersheet/charactersheet/templates/common/wizard_profile_step.tmpl.html, charactersheet/charactersheet/viewmodels/character/stats.js, charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_profile_step.js, test/viewmodels/test_stats_tab.js
Exp now persists and other fixes to profile.
Fixes #896
=> Bug: Exp persist

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/dm/encounter_sections/npc.js, charactersheet/charactersheet/models/dm/encounter_sections/player_text.js, charactersheet/charactersheet/models/dm/encounter_sections/player_text_section.js, charactersheet/charactersheet/templates/dm/encounter_sections/player_text_section.tmpl.html, charactersheet/charactersheet/utilities/convineince.js, charactersheet/charactersheet/viewmodels/dm/encounter.js, charactersheet/charactersheet/viewmodels/dm/encounter_detail.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/player_text_section.js, test/viewmodels/dm/test_encounter_detail.js
Adds new player text section.
Fixes #1023 
None
=> Adds Player Text Section

README.md, charactersheet/charactersheet/components/markdown-edit-preview.js, charactersheet/charactersheet/models/common/armor.js, charactersheet/charactersheet/templates/character/armors.tmpl.html, charactersheet/charactersheet/templates/character/notes.tmpl.html, charactersheet/charactersheet/templates/common/wizard_intro_step.tmpl.html, charactersheet/charactersheet/templates/common/wizard_player_type_step.tmpl.html, charactersheet/charactersheet/utilities/view_model_utilities.js, charactersheet/charactersheet/viewmodels/character/armor.js, charactersheet/charactersheet/viewmodels/character/player_image.js, package.json, test/characters/jebeddo_data.js, test/models/test_armor.js, test/viewmodels/test_armor.js
Add armor equipped checkbox
Fixes #972
=> Add armor equipped checkbox

charactersheet/charactersheet/index.html
Change new modal title to include campaign
Fixes #1040
=> Change new modal title to include campaign

charactersheet/charactersheet/templates/character/armors.tmpl.html
PR #962 incorrectly overwrote Armor templates. This replaces it with the correct version.
Fixes #952 again...
None
@adventurerscodex/core-developers Please confirm this is correct.
=> Replaces incorrectly merged armor template.

charactersheet/charactersheet/models/common/magic_item.js, charactersheet/charactersheet/viewmodels/character/magic_items.js, test/viewmodels/test_magic_items.js
Resolve issue where empty weight produced NAN
Fixes #1037
=> Resolve issue where empty weight produced NAN

charactersheet/charactersheet/models/common/character.js
Fix version set for database version on character import
Fixes #1036
=> Fix version set for database version on character import

charactersheet/charactersheet/index.html, charactersheet/site.css
Adds footer to wizard.
Footer is now sticky.
Fixed #938 
None
=> Adds sticky wizard footer.

charactersheet/charactersheet/models/dm/encounter_sections/environment_section.js, charactersheet/charactersheet/models/dm/encounter_sections/notes_section.js, charactersheet/charactersheet/models/dm/encounter_sections/npc_section.js, charactersheet/charactersheet/models/dm/encounter_sections/player_text_section.js, charactersheet/charactersheet/models/dm/encounter_sections/point_of_interest_section.js, charactersheet/charactersheet/templates/dm/encounter.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_detail.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/environment_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/notes_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/npc_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/player_text_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/point_of_interest.tmpl.html, charactersheet/charactersheet/viewmodels/dm/encounter_section_visibility.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/environment_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/notes_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/npc_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/player_text_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section.js
- Adds Encounter Section Taglines to Modal 
Fixed #1053 
None
=> Adds Encounter Section Taglines to Modal 

charactersheet/charactersheet/index.html
This file was mistakenly included after merge.
Fixes #1065
=> Removes unneeded file causing 404.

charactersheet/charactersheet/index.html
Updates export modal text
Fixes #1066 
None
=> Changes modal text

charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_profile_step.js
Fixes an issue that would cause the player to not be able to make a new character in the wizard.
None Logged
None
None
=> Replaces the background field in the wizard.

charactersheet/charactersheet/templates/dm/encounter.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_detail.tmpl.html
Fixes double HR at the bottom of section modal.
#1063
=> Fixes HR issue.

charactersheet/charactersheet/templates/dm/encounter_sections/monster_section.tmpl.html, charactersheet/charactersheet/viewmodels/dm/encounter_sections/monster_section.js
Add modal now only needs one click to open.
#1079
=> Monster opening modal fix

charactersheet/charactersheet/components/nested-list.js, charactersheet/site.css
Change trash to red for glyphicos on hover
Fixes #1083
=> Change trash to red for glyphicos on hover

charactersheet/charactersheet/models/dm/encounter_sections/encounter_coins.js, charactersheet/charactersheet/models/dm/encounter_sections/encounter_item.js, charactersheet/charactersheet/templates/dm/encounter_sections/monster_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/npc_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/player_text_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/point_of_interest.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/treasure_section.tmpl.html, charactersheet/charactersheet/viewmodels/dm/encounter_sections/monster_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/npc_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/player_text_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/treasure_section.js
Adds first element in focus to all DM modals.
#1045
=> Adds modal focus to all DM sections

charactersheet/charactersheet/viewmodels/dm/encounter.js, charactersheet/charactersheet/viewmodels/dm/encounter_cell.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/notes_section.js, test/viewmodels/dm/test_encounter_detail.js
- Adds a new method that reloads the cell data.
- Encounter calls it on it's children.
Fixed #1076
None
None
=> Fixes issue where Encounter Cells did not refresh their data.

charactersheet/charactersheet/models/dm/encounter_sections/monster_section.js, charactersheet/charactersheet/templates/dm/encounter_sections/npc_section.tmpl.html, charactersheet/charactersheet/viewmodels/dm/overview.js
- Fixes tense of Encounter Section Titles
- Campaign VM now unsubscribes from Notifications on unload.
Fixed #1086 
None
None
=> Updates Encounter section titles and fixes issue with Notifications

charactersheet/charactersheet/index.html
Added new footer icons and made them open in a new tab when clicked.
Fixes #1092
=> New Footer Icons

charactersheet/charactersheet/models/character/appearance.js, charactersheet/charactersheet/models/character/daily_feature.js, charactersheet/charactersheet/models/character/feat_traits.js, charactersheet/charactersheet/models/character/feats_prof.js, charactersheet/charactersheet/models/character/health.js, charactersheet/charactersheet/models/character/hit_dice_type.js, charactersheet/charactersheet/models/character/other_stats.js, charactersheet/charactersheet/models/character/saving_throws.js, charactersheet/charactersheet/models/character/skill.js, charactersheet/charactersheet/models/character/spell_slot.js, charactersheet/charactersheet/models/common/spell.js, test/characters/jebeddo_data.js, test/models/test_slots.js
Adds auto-ignore to all models and fixes tests
Fixes #1093
=> Adds auto-ignore to all models

charactersheet/charactersheet/templates/common/wizard_profile_step.tmpl.html, charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_profile_step.js
Add backgrounds to wizard
Fixes #1110
=> Add backgrounds to wizard

charactersheet/charactersheet/index.html
Fixed feed.xml and changed all external links to open in a new window instead of opening in the same tab.
Fixes #1097
=> Fixed feed.xml

charactersheet/charactersheet/index.html
Change new link to new/import
Fixes #1116
=> Change new link to new/import

charactersheet/charactersheet/models/dm/encounter_sections/monster.js, charactersheet/charactersheet/models/dm/encounter_sections/monster_ability_score.js, test/models/dm/encounter_sections/test_encounter_armor.js, test/models/dm/encounter_sections/test_encounter_coins.js, test/models/dm/encounter_sections/test_encounter_item.js, test/models/dm/encounter_sections/test_encounter_magic_item.js, test/models/dm/encounter_sections/test_encounter_weapon.js, test/models/dm/encounter_sections/test_environment.js, test/models/dm/encounter_sections/test_environment_section.js, test/models/dm/encounter_sections/test_monster.js, test/models/dm/encounter_sections/test_monster_ability_score.js, test/models/dm/encounter_sections/test_monster_section.js, test/models/dm/encounter_sections/test_notes_section.js, test/models/dm/encounter_sections/test_npc.js, test/models/dm/encounter_sections/test_npc_section.js, test/models/dm/encounter_sections/test_player_text.js, test/models/dm/encounter_sections/test_player_text_section.js, test/models/dm/encounter_sections/test_point_of_interest.js, test/models/dm/encounter_sections/test_point_of_interest_section.js, test/models/dm/encounter_sections/test_treasure_section.js, test/models/dm/test_campaign.js
Adds tests to all DM tools models and made minor fixes to logic in some models.
=> DM Tools model tests

charactersheet/charactersheet/models/common/armor.js, test/models/test_armor.js
AC should not show in the label if there is no AC
Fixes #1081
=> AC should not show in the label if there is no AC

charactersheet/charactersheet/viewmodels/dm/overview.js
Removed duplicate property on overview.
Fixes #1125
=> Removed unnecissary date

charactersheet/charactersheet/models/common/item.js, charactersheet/charactersheet/models/common/magic_item.js, charactersheet/charactersheet/models/dm/encounter_sections/npc.js, charactersheet/charactersheet/models/dm/encounter_sections/player_text.js, charactersheet/charactersheet/models/dm/encounter_sections/point_of_interest.js, charactersheet/charactersheet/templates/dm/encounter_sections/point_of_interest.tmpl.html, charactersheet/charactersheet/utilities/convineince.js, test/models/dm/encounter_sections/test_encounter_item.js, test/models/dm/encounter_sections/test_encounter_magic_item.js, test/models/dm/encounter_sections/test_npc.js, test/models/dm/encounter_sections/test_player_text.js
Changed how and when strings get truncated. Added a new convenience method to reduce boilerplate.
Fixes #1031
=> Truncation changes

charactersheet/charactersheet/index.html, charactersheet/charactersheet/init.js, charactersheet/charactersheet/services/status_service_components/inspiration_component.js, charactersheet/charactersheet/viewmodels/character/stats.js, charactersheet/charactersheet/viewmodels/character/status_line.js
- Adds new inspired status line component for players.
- Nothing shows if the player isn't inspired.
- Refactors status line vm to present a nicer sentence.
Fixes #1117 
None
=> Adds new inspired status line component for players.

charactersheet/bin/popover_bind.js, charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/character/other_stats.js, charactersheet/charactersheet/templates/character/other_stats.tmpl.html, charactersheet/charactersheet/viewmodels/character/stats.js
Add popovers for auto calc info
Fixes #812
=> Add popovers for auto calc info

charactersheet/charactersheet/models/common/armor.js, charactersheet/charactersheet/models/common/item.js, charactersheet/charactersheet/models/common/magic_item.js, charactersheet/charactersheet/models/common/weapon.js, charactersheet/charactersheet/templates/character/items.tmpl.html, charactersheet/charactersheet/templates/character/magic_items.tmpl.html
Added cost label to card and table. Also fixed weight label logic for various other models.
Fixes #1140
=> Adding cost to inventory card/table

charactersheet/charactersheet/models/dm/encounter_sections/monster.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/templates/dm/encounter_sections/monster_section.tmpl.html, charactersheet/charactersheet/viewmodels/dm/encounter_sections/monster_section.js, test/models/dm/encounter_sections/test_monster.js
Added monster pre population, OGL disclaimer, cancel button to add monster modal.
Fixes #1101
=> Pre-pop monsters

.gitignore, test/viewmodels/dm/test_environment_section.js, test/viewmodels/dm/test_monster_section.js, test/viewmodels/dm/test_notes_section.js, test/viewmodels/dm/test_npc_section.js, test/viewmodels/dm/test_player_text.js, test/viewmodels/dm/test_point_of_interest_section.js, test/viewmodels/dm/test_treasure_section.js
Added tests to DM tools VM
Fixes #1044
=> DM Tools Tests

.gitignore, .vscode/settings.json, charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/character/proficiency.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/templates/character/feats_prof.tmpl.html, charactersheet/charactersheet/templates/character/index.tmpl.html, charactersheet/charactersheet/templates/character/proficiencies.tmpl.html, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/character/proficiencies.js, charactersheet/charactersheet/viewmodels/character/skills_tab.js, test/models/test_proficiency.js, test/viewmodels/test_proficiencies.js
Added proficiency table to skills.
Fixes #1145
_Note: The UI won't remain like this. I didn't feel it worth the time to fix the UI for one new table when we're going to be adding three more later on._
Mobile:
=> Proficiency and language

charactersheet/charactersheet/templates/character/spells.tmpl.html, charactersheet/charactersheet/viewmodels/character/spells.js, test/viewmodels/test_spells.js
Fixed bug with prepared spells.
Fixes #1186
=> Prepared spells bug

.vscode/settings.json, charactersheet/charactersheet/models/character/other_stats.js, charactersheet/charactersheet/templates/character/other_stats.tmpl.html, charactersheet/charactersheet/templates/character/saving_throws.tmpl.html, charactersheet/charactersheet/viewmodels/character/ability_scores.js, charactersheet/charactersheet/viewmodels/character/stats.js, charactersheet/site.css
Adds popover for proficiency and initiative.
Fixes #1134 
Popover:
=> Adds Tooltips

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/character/trait.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/templates/character/index.tmpl.html, charactersheet/charactersheet/templates/character/traits.tmpl.html, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/character/skills_tab.js, charactersheet/charactersheet/viewmodels/character/traits.js, test/models/test_trait.js, test/viewmodels/test_traits.js
Add traits functionality
Fixes #1183
=> Add traits functionality

charactersheet/charactersheet/models/common/armor.js, charactersheet/charactersheet/models/common/item.js, charactersheet/charactersheet/models/common/magic_item.js, charactersheet/charactersheet/models/common/weapon.js, test/models/test_armor.js, test/models/test_item.js, test/models/test_magic_item.js, test/models/test_weapon.js
=> Fix weight label

charactersheet/charactersheet/models/character/trait.js, charactersheet/charactersheet/templates/character/traits.tmpl.html, charactersheet/charactersheet/viewmodels/character/traits.js
Add race to traits
Fixes #1199
=> Add race to traits

charactersheet/charactersheet/index.html, charactersheet/charactersheet/init.js, charactersheet/charactersheet/models/character/feature.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/templates/character/features.tmpl.html, charactersheet/charactersheet/templates/character/index.tmpl.html, charactersheet/charactersheet/utilities/data_repository.js, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/character/features.js, charactersheet/charactersheet/viewmodels/character/skills_tab.js, test/models/test_feature.js, test/viewmodels/test_features.js
Add features functionality
Fixes #1182
=> Add features functionality

charactersheet/charactersheet/services/common/shared_service_manager.js
Services/Architecture
None Logged.
Use this shared service manager to create all global shared services, if possible.
None
=> Adds new shared service manager for more easily creating services.

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/character/saving_throws.js, charactersheet/charactersheet/models/character/skill.js, charactersheet/charactersheet/models/common/weapon.js, charactersheet/charactersheet/services/character/proficiency_service.js, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/character/character_root.js, charactersheet/charactersheet/viewmodels/character/skills.js, charactersheet/charactersheet/viewmodels/character/stats.js, karma.conf.js, test/models/test_saving_throws.js, test/models/test_skill.js, test/models/test_weapon.js, test/services/test_proficiency_service.js
* Fixes all models and view models that use proficiency
* Fully tested service
* Fix broken tests
Fixes #1208 
Fixes #1201
=> Adds proficiency service

charactersheet/charactersheet/templates/character/feats.tmpl.html, charactersheet/charactersheet/templates/character/features.tmpl.html, charactersheet/charactersheet/templates/character/tracker.tmpl.html, charactersheet/charactersheet/templates/character/traits.tmpl.html, charactersheet/charactersheet/viewmodels/character/feats.js, charactersheet/charactersheet/viewmodels/character/features.js, charactersheet/charactersheet/viewmodels/character/traits.js, test/viewmodels/test_feats.js, test/viewmodels/test_features.js, test/viewmodels/test_traits.js
Makes skills UI look better by removing description column.
=> Makes skills tab look better

charactersheet/charactersheet/templates/character/index.tmpl.html
=> Fix skills layout

charactersheet/charactersheet/templates/character/index.tmpl.html
=> Change armor-heading to remind users to don armor and shields

charactersheet/charactersheet/templates/character/armors.tmpl.html
=> Add number type to weight modals for add and edit

charactersheet/charactersheet/init.js, charactersheet/charactersheet/settings.js
=> Added filter for license

charactersheet/charactersheet/templates/dm/encounter_sections/npc_section.tmpl.html, charactersheet/charactersheet/viewmodels/dm/encounter_sections/npc_section.js
Add pre-pop to race input for npcs
Fixes #1227
=> Add pre-pop to race input for npcs

charactersheet/charactersheet/templates/character/features.tmpl.html, charactersheet/charactersheet/viewmodels/character/features.js
Add pre-pop to class input in features
Fixes #1225
=> Add pre-pop to class input in features

charactersheet/charactersheet/templates/character/traits.tmpl.html, charactersheet/charactersheet/viewmodels/character/traits.js
Add pre-pop to race input for traits
Fixes #1226
=> Add pre-pop to race input for traits

package.json
* Replaces "phantomjs" with "phantomjs-prebuilt"
* #1105 
This patch uses "phantomjs-prebuilt" instead of "phantomjs" as per instructions during installation:
```
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
```
Upon installation, the following message will no longer appear:
```
Running "karma:test" (karma) task                                                                                                                                                                                                                                      [136/221]
19 03 2017 16:12:08.836:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
19 03 2017 16:12:08.841:INFO [launcher]: Starting …
```
=> Replace phantomjs with phantomjs-prebuilt. Fixes #1105

charactersheet/charactersheet/templates/character/feats.tmpl.html, charactersheet/charactersheet/templates/character/features.tmpl.html, charactersheet/charactersheet/templates/character/index.tmpl.html, charactersheet/charactersheet/templates/character/proficiencies.tmpl.html, charactersheet/charactersheet/templates/character/traits.tmpl.html
Removed headers in new panels. Updated section header.
Fixes #1237
=> Removes headers from features, feats, traits, and profs

charactersheet/charactersheet/viewmodels/character/saving_throws.js, charactersheet/charactersheet/viewmodels/character/weapons.js, charactersheet/charactersheet/viewmodels/common/characters.js
=> Replaces jQuery

charactersheet/charactersheet/index.html
Add reddit link/icon to footer
Fixes #1244
=> Add reddit link/icon to footer

charactersheet/charactersheet/index.html
Add patreon link to navbar
Fixes #1245
=> Add patreon link to navbar

charactersheet/charactersheet/index.html, charactersheet/charactersheet/init.js, charactersheet/charactersheet/models/common/status_weight_pair.js, charactersheet/charactersheet/services/character/status_service_components/healthiness_component.js, charactersheet/charactersheet/templates/character/status_line.tmpl.html, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/viewmodels/character/stats.js
Added Healthiness component to status line.
Fixes #1263
Based on third party feedback, the status line was difficult to read when it was `small` and `italicized`. I have changed it to just be normal sized.
Screenshots of full to dead:
=> Healthiness status

charactersheet/charactersheet/index.html, charactersheet/charactersheet/init.js, charactersheet/charactersheet/models/common/status_weight_pair.js, charactersheet/charactersheet/services/character/status_service_components/tracked_component.js, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/character/tracker.js
Adds tracked abilities status component
Fixes #1265
=> Tracked ability status component

charactersheet/charactersheet/templates/character/profile.tmpl.html
Fixes issue with profile VM spamming the XMPP pubsub system.
Fixes #1275 
None
None
=> Fixes the profile spamming issue.

charactersheet/charactersheet/services/common/account/messaging/node_service.js, charactersheet/charactersheet/settings.js
Adds random fantasy room name generator.
Fixes #1262
=> Random fantasy room name generator

charactersheet/charactersheet/index.html
Removes old missing file
None logged
=> Removes old missing file

charactersheet/charactersheet/services/common/account/messaging/node_service.js, charactersheet/charactersheet/viewmodels/common/party_manager.js
Shows a user that they are subscribed to a room upon login. A toastr will also be dispatched.
Fixes #1273
=> Display party if subscribed to node

charactersheet/charactersheet/init.js, charactersheet/charactersheet/viewmodels/common/party_manager.js
Auto subscription checks the full jid before it subscribes.
=> Auto subscribe fixes

charactersheet/charactersheet/index.html
Add required snippets for google tag manager
#1291
=> Add snippets for google tag manager

charactersheet/charactersheet/models/common/player_info.js, test/fixtures.js
Use https when using gravatar
Fixes #1294
=> Use https when using gravatar

charactersheet/charactersheet/index.html
=> Fix link to blog

charactersheet/charactersheet/settings.js
Use min files for .json srd
Fixes #1297
=> Use min files for .json srd

charactersheet/charactersheet/index.html, charactersheet/site.css
Icon resolution is poor
Fixes #1303
=> Improve icon logo resolution

charactersheet/charactersheet/index.html, charactersheet/charactersheet/viewmodels/common/login.js
Add link to signup if user is not logged in
Fixes #1317
=> Add link to signup if user is not logged in

charactersheet/charactersheet/models/common/chat_message.js, charactersheet/charactersheet/models/common/note.js, charactersheet/charactersheet/templates/common/chat.tmpl.html, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/character/character_root.js, charactersheet/charactersheet/viewmodels/character/notes.js, charactersheet/charactersheet/viewmodels/common/chat/chat_detail.js, charactersheet/site.css
Chat messages can now be saved to Notes under a new note type.
Fixes #1309 
None
Can't get screenshot atm.
=> Adds "Save to Notes" to chat messages.

charactersheet/charactersheet/services/common/account/authentication_service.js
- Invalid tokens in the URL no longer cause login to display empty name field.
- Adds automatic retry with local token if URL token is invalid (bookmarked links).
Fixes #1321 
None
None
=> Updates Auth flow

charactersheet/charactersheet/models/common/character.js, charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_intro_step.js
Fixes character import/export unicode parsing issue
Fixes #1293 
None
None
=> Fixes character import/export unicode parsing issue

charactersheet/charactersheet/utilities/character_manager.js, charactersheet/charactersheet/viewmodels/common/root.js, charactersheet/charactersheet/viewmodels/common/wizard.js
Character Manager, Wizard
- Fixes #1338
- Fixes issue that would cause the wizard to load into the wrong step.
- Fixes an issue where the character picker would be incorrectly shown.
- Fixes issue where a default character would be chosen. 
None
None
=> Fixes Multiple Issues With Character Switching/Loading

charactersheet/charactersheet/models/common/chat_room.js, charactersheet/charactersheet/services/common/account/messaging/chat_service.js, charactersheet/charactersheet/viewmodels/common/chat/chat.js, charactersheet/charactersheet/viewmodels/common/chat/chat_detail.js
- Cleans up code to use more consistent conventions.
- Chat detail view is now aware of party events and updates itself accordingly.
- Chat detail view now displays a template image if no pCard is present for user.
- Removed some debug logging.
- Fixes an issue where the first chat room would not be selected by default on party join.
Fixes #1330 
Fixes #1322 
None
None
=> Fixes multiple issues with chat.

charactersheet/charactersheet/models/common/chat_message.js
"Save to chat" now adds the timestamp as well.
None logged
None
=> Updates "save to chat" message formatting.

charactersheet/charactersheet/templates/character/items.tmpl.html, charactersheet/charactersheet/templates/character/magic_items.tmpl.html, charactersheet/charactersheet/templates/character/stats.tmpl.html, charactersheet/charactersheet/viewmodels/character/profile.js, charactersheet/charactersheet/viewmodels/character/spell_stats.js, charactersheet/charactersheet/viewmodels/character/stats.js
Fixed special characters not rendering correctly in descriptions.
Fixed issues with fields in dashboard not updating.
=> Dashboard fixes

charactersheet/charactersheet/components/nested-list.js, charactersheet/charactersheet/viewmodels/dm/encounter_cell.js
- Removes unnecessary condition for encounter add button.
Fixed #1352
None
=> Fixes issue where encounter cell delete icon was not displayed.

charactersheet/charactersheet/viewmodels/common/chat/chat.js
Rooms are no longer created if there are not invitees at creation time.
Fixed #1354
None
None
=> Adds check for at least 1 invitee before creating room.

charactersheet/charactersheet/templates/common/character_picker.tmpl.html
- Character Picker now also references campaigns
- Adjusted formatting
Fixes #1351 
None
=> Fixes issue with label text and formatting.

charactersheet/charactersheet/index.html, charactersheet/charactersheet/templates/character/items.tmpl.html, charactersheet/charactersheet/templates/character/magic_items.tmpl.html, charactersheet/charactersheet/templates/character/stats.tmpl.html, charactersheet/charactersheet/viewmodels/character/profile.js, charactersheet/charactersheet/viewmodels/character/spell_stats.js, charactersheet/charactersheet/viewmodels/character/stats.js, charactersheet/charactersheet/viewmodels/common/root.js
Party manager modal always opens to join tab if the character has at least one party.
Fixes #1339
=> Party manager modal update

charactersheet/charactersheet/viewmodels/character/stats.js
Fixed hit dice rest logic
Fixes #1361
=> Long rest hit dice reset

charactersheet/charactersheet/templates/common/characters.tmpl.html
'More info' link removed. 
Fixes #1223
=> Removes more info link so that it can be added back later.

charactersheet/charactersheet/models/common/chat_message.js, charactersheet/charactersheet/viewmodels/common/chat/chat.js
Fix two chat errors being thrown.
@Sonictherocketman Please look over the fix before you approve.
In the chat view model, the objects were sent in the wrong order, so it wasn't working, not sure if it ever was working.
The other issue in the chat_message model was because the roster was undefined and you were trying to get stuff from an undefined object. I added a simple check for that. It seems to work fine now.
Fixes #1359
=> Chat errors

charactersheet/charactersheet/viewmodels/common/root.js
- Forces view models to unload when switching to the wizard.
- Removes redundant update in app state on load
Fixes #1348 
None 
None
=> Forces view models to unload when switching to the wizard.

charactersheet/charactersheet/services/common/account/messaging/chat_service.js, charactersheet/charactersheet/services/common/sync/card_service.js, charactersheet/charactersheet/viewmodels/dm/party.js
Fixed bug that sometimes displayed two of the same character, where one was old and one was new. card_service also got this update.
None logged
=> Dashboard: Fix duplicate players

charactersheet/charactersheet/viewmodels/common/chat/chat.js
Ignores toaster/chat messages from yourself.
Fixes #1366
=> Multiple toastr/chat messages

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/common/character.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/utilities/convenience.js, charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_intro_step.js, charactersheet/charactersheet/viewmodels/dm/party.js
Adds dropbox save, fixes issue with dashboard, and fixes dropbox import.
=> Dropbox save

charactersheet/charactersheet/services/common/account/messaging/node_service.js, charactersheet/charactersheet/services/common/sync/card_service.js
=> Removed debug logging

charactersheet/charactersheet/templates/common/party_manager.tmpl.html
Removes party link from party mananger
None logged
=> Removes party link from party mananger

charactersheet/charactersheet/services/common/account/messaging/chat_service.js
Checks if incoming message is blank before saving.
Fixes #1381 
Fixes #1382
=> Blank toastr fix

charactersheet/charactersheet/services/common/account/xmpp_connection_service.js, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/common/party_manager.js, charactersheet/charactersheet/viewmodels/common/user_notification.js
- Adds new conneciton error messages for the user.
- Users are now unable to join/manage their party if the connection failed to establish.
- Toastr messages sent via UserNotifications now also pass an optional `args`
parameter to configure the notification.
- Added new signals to support this feature, and additional docs.
Fixes #1389 
Possibly fixes #1395 
None
=> Adds new conneciton error messages for the user.

charactersheet/charactersheet/services/common/account/authentication_service.js, charactersheet/charactersheet/viewmodels/common/root.js
- Refactors User Authentication and alerts user of errors with their account
- Promotes UserNotification VM to load regardless of characters/campaigns selected.
Fixes #1390 
Possibly fixes #1395 
Depends on #1398 (core)
Depends on [#65](https://github.com/adventurerscodex/api.adventurerscodex/pull/65) (api)
=> Refactors User Authentication and alerts user of errors with their account

charactersheet/charactersheet/index.html
- Player name no longer checks spelling after editing.
None logged.
None
None
=> Player name no longer checks spelling after editing.

charactersheet/charactersheet/services/character/sync/character_card_fields.js, charactersheet/charactersheet/services/common/account/messaging/chat_service.js, charactersheet/charactersheet/services/dm/sync/dm_card_fields.js, charactersheet/charactersheet/viewmodels/common/chat/chat.js
- Fixes an issue where leaving a party did not purge the chat history.
- Fixes an issue where chat messages would not be displayed (from v1.4.1).
- Fixes an issue where cards did not posses images (from v1.4.1)
Fixes #1391 
None logged
None logged.
=> Fixes multiple chat issues.

charactersheet/charactersheet/index.html
=> Remove google analytics code

charactersheet/charactersheet/services/common/account/messaging/chat_service.js
Fixes issues with invites/private chat.
None logged.
None logged.
None logged.
=> Fixes issues with chat invites in Prod

charactersheet/charactersheet/index.html
Main logo and app name will take you to app.ac.com
Blog will now take you to ac.com
Fixes #1383
=> Navbar link updates

CHANGELOG.md, charactersheet/charactersheet/settings.js, package.json
=> Updates changelog

CHANGELOG.md, charactersheet/charactersheet/index.html, charactersheet/charactersheet/services/character/sync/character_card_fields.js, charactersheet/charactersheet/services/common/account/authentication_service.js, charactersheet/charactersheet/services/common/account/messaging/chat_service.js, charactersheet/charactersheet/services/common/account/xmpp_connection_service.js, charactersheet/charactersheet/services/dm/sync/dm_card_fields.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/common/chat/chat.js, charactersheet/charactersheet/viewmodels/common/party_manager.js, charactersheet/charactersheet/viewmodels/common/root.js, charactersheet/charactersheet/viewmodels/common/user_notification.js, package.json
* Changes where the navbar links take you
* Fixes bug with private chats
* Removes google analytics code
* Fixes bug where chat history was not purged when you left a party
* Fixes issue where the character/campaign name was autocorrected
* Updates handling of error messages
* Fixes issue with blank message in chat
=> Version 1.4.2

charactersheet/charactersheet/services/character/sync/character_card_fields.js
Fixes passive int for dashboard.
Fixes #1418
=> Fixes passive int on dashboard

charactersheet/charactersheet/viewmodels/common/party_manager.js
Add link to connection issues faq for connection errors
Fixes #1436
=> Add link to connection issues faq for connection errors

charactersheet/charactersheet/index.html, charactersheet/charactersheet/templates/common/player_image.tmpl.html, charactersheet/style/site.css
Improves the look of the Mobile Header for the app.
Fixes #1442
=> Adds new responsive text alignment styles, and refactors header

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/common/message.js, charactersheet/charactersheet/models/common/presence.js, charactersheet/charactersheet/models/dm/encounter_sections/player_text.js, charactersheet/charactersheet/services/common/account/messaging/chat_message_types.js, charactersheet/charactersheet/services/common/account/messaging/chat_service.js, charactersheet/charactersheet/templates/common/chat/chat.tmpl.html, charactersheet/charactersheet/templates/common/chat/read_aloud_item.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/player_text_section.tmpl.html, charactersheet/charactersheet/viewmodels/common/chat/chat.js, charactersheet/charactersheet/viewmodels/common/chat/chat_detail.js, charactersheet/charactersheet/viewmodels/common/chat/chat_log_read_aloud_item.js, charactersheet/charactersheet/viewmodels/common/chat/chat_log_system_item.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/player_text_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/player_text_section_push_modal.js, charactersheet/style/site.css
Read Aloud text can now be pushed to party members.
Fixes #1408 
None
=> Push readalout

charactersheet/charactersheet/viewmodels/character/stats.js
Adds notification when a user fails all three death saves.
Fixes #466 
None
=> Adds death save notification

charactersheet/charactersheet/templates/common/character_picker.tmpl.html
Fixes issue with character picker images being oblong.
None logged
None
=> Fixes picker styling

charactersheet/charactersheet/templates/character/skills.tmpl.html, charactersheet/charactersheet/viewmodels/character/skills.js, test/viewmodels/test_skills.js
> He reached into the depths of the past... and copy-pasted he way out.
- Adds modal for adding skills.
- Skill ability score can only be set during add.
- Skills can now be deleted.
Fixes #858 
None
=> Allows custom skills to be added and skills to be deleted

charactersheet/charactersheet/services/common/account/messaging/chat_service.js
- Fixes an issue where parties might not be saved.
Fixes #1433 
None
None
=> Fixes issue where chat rooms might not be detected if another character/campaign already has joined.

charactersheet/charactersheet/viewmodels/common/party_manager.js
- Adds check for null party and normalizes inputted party to lower.
- Also adds check for min-length room before allowing join.
Fixes #1397 
None
None
=> Adds check for null party and normalizes inputted party to lower.

charactersheet/charactersheet/models/common/campaign_map_or_image.js, charactersheet/charactersheet/services/common/sync/image_service.js, charactersheet/charactersheet/templates/dm/campaign_maps_and_images.tmpl.html, charactersheet/charactersheet/viewmodels/dm/campaign_maps_and_images.js
Adds exhibit to campaign maps and images.
=> Adds exhibit to campaign maps and images.

charactersheet/charactersheet/viewmodels/common/chat/chat_log_image_item.js
Chat image messages now have saved timestamps
None logged.
None logged
None logged.
=> Adds date to saved images

charactersheet/charactersheet/models/common/campaign_map_or_image.js, charactersheet/charactersheet/models/common/map_or_image.js, charactersheet/charactersheet/viewmodels/character/exhibit.js, charactersheet/style/site.css
Changes toastr messages for chat images.
Adds toastr for image on exhibit
=> Minor fixes

charactersheet/charactersheet/models/common/campaign_map_or_image.js, charactersheet/charactersheet/models/common/map_or_image.js, charactersheet/charactersheet/templates/dm/index.tmpl.html, charactersheet/charactersheet/viewmodels/character/exhibit.js, charactersheet/style/site.css
=> Tab reorder

charactersheet/charactersheet/templates/dm/campaign_maps_and_images.tmpl.html
=> Fix issue with add maps and images modal not opening

charactersheet/charactersheet/utilities/fixtures.js
=> Add subraces

charactersheet/charactersheet/utilities/fixtures.js
Reverts adventurerscodex/adventurerscodex#1467
=> Revert "Add subraces"

charactersheet/charactersheet/templates/common/characters.tmpl.html
- Fixes issue with character pictures displaying as ellipses in char picker.
None logged
None
=> Fixes issue with ellipse pictures in the picker

charactersheet/charactersheet/viewmodels/dm/encounter_detail.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/environment_section.js, test/viewmodels/dm/test_encounter_detail.js
- Unloading an encounter no longer triggers a save.
- Environments now save on value update.
None logged
=> Improves encounter switching speed.

charactersheet/charactersheet/templates/common/player_image.tmpl.html, charactersheet/charactersheet/viewmodels/common/player_image.js, charactersheet/style/site.css
- Adds new indicator for players/dms to know when and if they're connected to XMPP.
None logged
None
=> Adds new XMPP connection status indicator to player image.

charactersheet/charactersheet/templates/common/master-detail/master.tmpl.html, charactersheet/charactersheet/viewmodels/common/master_detail.js
Chat detail now uses more of the space in the window.
None logged
None
=> Formats chat like encounters

charactersheet/charactersheet/index.html, charactersheet/charactersheet/viewmodels/common/characters.js
Hides dropbox export for users that aren't logged in.
None logged.
None logged
=> Dropbox export is no longer shown to non-logged in users.

charactersheet/charactersheet/components/nested-list.js, charactersheet/charactersheet/models/dm/encounter.js, charactersheet/charactersheet/viewmodels/dm/encounter.js, charactersheet/charactersheet/viewmodels/dm/encounter_cell.js
- Encounters now remember that they're collapsed on reload.
Fixes #1434
=> Encounters now remember if they're collapsed

charactersheet/charactersheet/index.html, charactersheet/charactersheet/viewmodels/character/character_root.js, charactersheet/charactersheet/viewmodels/dm/dm_root.js
Adds status line for what party you're connected to.
=> Adds status line for what party you're connected to.

charactersheet/charactersheet/templates/character/armors.tmpl.html, charactersheet/charactersheet/templates/character/feats.tmpl.html, charactersheet/charactersheet/templates/character/features.tmpl.html, charactersheet/charactersheet/templates/character/items.tmpl.html, charactersheet/charactersheet/templates/character/magic_items.tmpl.html, charactersheet/charactersheet/templates/character/proficiencies.tmpl.html, charactersheet/charactersheet/templates/character/saving_throws.tmpl.html, charactersheet/charactersheet/templates/character/skills.tmpl.html, charactersheet/charactersheet/templates/character/spell_slots.tmpl.html, charactersheet/charactersheet/templates/character/spell_stats.tmpl.html, charactersheet/charactersheet/templates/character/spells.tmpl.html, charactersheet/charactersheet/templates/character/stats.tmpl.html, charactersheet/charactersheet/templates/character/tracker.tmpl.html, charactersheet/charactersheet/templates/character/traits.tmpl.html, charactersheet/charactersheet/templates/character/weapons.tmpl.html, charactersheet/charactersheet/templates/dm/campaign_maps_and_images.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_detail.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/environment_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/notes_section.tmpl.html, charactersheet/style/site.css
- Applies this class to both characters and DMs (encounters not included).
**This isn't a done deal. I just wanted to see what it would look like so we could discuss**.
None logged
None
=> Adds new tight-inner panel class that saves some space with tables.

charactersheet/charactersheet/settings.js, charactersheet/charactersheet/templates/common/wizard_profile_step.tmpl.html, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/viewmodels/common/wizard.js, charactersheet/charactersheet/viewmodels/common/wizard_steps/wizard_profile_step.js, test/fixtures.js, test/viewmodels/test_wizard_profile.js
Add populate backpacks
Fixes #1495
=> Add populate backpacks

charactersheet/charactersheet/index.html, charactersheet/charactersheet/init.js, charactersheet/charactersheet/services/common/account/notification_service.js, charactersheet/charactersheet/utilities/convenience.js, charactersheet/charactersheet/viewmodels/common/root.js
- Adds notifications service
- Supports new persistent and temp notifications
- Adds new OAuth PUT method
None logged
None
=> Adds notifications service

charactersheet/charactersheet/index.html, charactersheet/charactersheet/templates/character/exhibit.tmpl.html, charactersheet/charactersheet/templates/common/master-detail/master.tmpl.html, charactersheet/charactersheet/templates/common/party_manager.tmpl.html, charactersheet/charactersheet/templates/dm/campaign_maps_and_images.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/environment_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/maps_and_images_section.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/player_text_section.tmpl.html, charactersheet/charactersheet/templates/dm/party.tmpl.html, charactersheet/charactersheet/viewmodels/character/character_root.js, charactersheet/charactersheet/viewmodels/character/exhibit.js, charactersheet/charactersheet/viewmodels/common/chat/chat.js, charactersheet/charactersheet/viewmodels/common/party_manager.js, charactersheet/charactersheet/viewmodels/dm/campaign_maps_and_images.js, charactersheet/charactersheet/viewmodels/dm/dm_root.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/environment_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/player_text_section.js, charactersheet/charactersheet/viewmodels/dm/party.js, charactersheet/style/site.css
Makes all things that require a connection to be shown by default. 
Fixes #1478 
Fixes #1415
=> Show party content offline

charactersheet/charactersheet/models/character/health.js, charactersheet/charactersheet/templates/character/stats.tmpl.html, test/viewmodels/test_stats.js
Remove ko from hp bar
Fixes #1514
=> Remove ko from hp bar

charactersheet/charactersheet/services/common/account/xmpp_connection_service.js, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/common/party_manager.js
- The XMPP connection is now able to detect account conflicts.
- Notifications are dispatched to conflicted clients.
None logged
None
None
=> Adds account conflict detection

charactersheet/charactersheet/services/common/account/messaging/node_service.js, charactersheet/charactersheet/viewmodels/character/exhibit.js
=> Reduces notification spam.

charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/character/character_root.js, charactersheet/charactersheet/viewmodels/character/exhibit.js, charactersheet/charactersheet/viewmodels/dm/dm_root.js
Fixes issue with name of node changing when you join chat rooms.
=> Fixes issue with exhibits going away when players send cards.

charactersheet/charactersheet/templates/dm/campaign_maps_and_images.tmpl.html, charactersheet/charactersheet/templates/dm/encounter_sections/maps_and_images_section.tmpl.html, charactersheet/charactersheet/viewmodels/dm/campaign_maps_and_images.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section.js
Adds the dropbox link converter to campaign/encounter maps and images.
Fixes #1523
=> Adds the dropbox link converter to campaign/encounter maps and images.

charactersheet/charactersheet/viewmodels/common/user_notification.js
Changed toastr config to not allow duplicate toastrs.
Fixes #1528
=> Don't allow duplicate toastrs

charactersheet/charactersheet/viewmodels/common/party_manager.js
Updated inAParty boolean when reconnected to XMPP.
Fixes #1532
=> Party Manager Modal bug

package.json, webpack.config.js
* Install loaders
* Add html-loader to rules key (loaders key is deprecated)
=> Instal loaders and fix html loader

.travis.yml, test/models/test_character.js
Travis should run the linting
N/A (sorry @tanyxp)
=> Add lint to travis

package-lock.json, package.json
- Uses local not global `webpack`
=> Updates production and testing build commands

package.json
Remove unused prod dependencies
=> Remove unused prod dependencies

.travis.yml, scripts/deploy.sh
- Adds new post_build script for Travis to push to Prod and Nightly after merge.
- None logged
=> Adds Continuous Deployment Script to Travis 

charactersheet/charactersheet/init.js, charactersheet/charactersheet/models/common/character.js, charactersheet/charactersheet/services/common/account/messaging/chat_service.js, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/viewmodels/common/chat/index.js, charactersheet/charactersheet/viewmodels/common/login/index.js, charactersheet/charactersheet/viewmodels/common/party_manager/index.js, webpack.dev.js, webpack.prod.js, webpack.test.js
=> Adds environment specific settings to webpack configs. 

karma.conf.js, test/models/test_saving_throws.js, test/utilities/test_sort_service.js, webpack.common.js
=> Adds isparta loader to make coverage work.

Gruntfile.js
We are only using grunt to send to coveralls, so the script is simplified.
=> Simplify grunt file

charactersheet/charactersheet/services/common/account/xmpp_connection_service.js, webpack.dev.js, webpack.prod.js, webpack.test.js
- Test server should have valid XMPP credentials now and Core has been updated to use them.
=> Adds new settings for Nightly XMPP Server

README.md
Readme fixes
None Logged
None logged
None
=> Updates readme with more info and new issue label guide.

src/charactersheet/viewmodels/common/party_status/index.js
=> Fixes party status name changing to private room names.

src/charactersheet/models/common/chat_room.js, src/charactersheet/models/common/presence.js, src/charactersheet/models/dm/encounter_sections/monster.js, src/charactersheet/services/character/sync/character_card_fields.js, src/charactersheet/services/common/account/xmpp_connection_service.js, src/charactersheet/services/common/sync/card_service.js, src/charactersheet/services/dm/sync/dm_card_fields.js
Fixes all but 5 circular reference
=> Fix more circular references

src/charactersheet/viewmodels/common/root/index.html, src/charactersheet/viewmodels/common/root/index.js, src/style/site.css, webpack.dev.js, webpack.prod.js, webpack.test.js
=> Adds build version and date to the app footer.

src/charactersheet/models/common/weapon.js
Fixes issue causing to hit modifier calculation error where str and dex not considered
#1602
=> Fix import issue causing to hit modifier calculation error

webpack.dev.js, webpack.prod.js, webpack.test.js
- Webpack config now sets global version # from property in the package.json.
None logged.
None
None
=> Version #s are now derived from package.json

src/index.html
- Fixes Favicon and Apple Touch Icon
None logged.
None 
None
=> Changes URL for images to static API resources.

src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/index.js
Fix issue where the edit treasure modal for coins wouldn't open.
Fixes #1607
=> Fix coins image 404

webpack.prod.js, webpack.test.js
- Adds missing import statements...
=> Adds imports to other configs.

src/charactersheet/migrations/150_1_dm_notes.js
=> Fixes issue with importing DM character

src/charactersheet/viewmodels/dm/encounter/index.js, src/charactersheet/viewmodels/dm/encounter_detail/index.js
=> Fixes some encounter issues

package.json
- Adds Preflight Command
None logged
None
None
=> Adds preflight command

src/charactersheet/viewmodels/common/root/index.html, src/charactersheet/viewmodels/common/root/index.js
- Adds banner to dev and test to differentiate them.
None logged
None
=> Adds banner for env differentiation

src/charactersheet/viewmodels/dm/encounter_sections/notes_section/index.js
- Fixes issue where encounter notes don't save
Fixes #1616 
None
None
=> Fixes notes subsciption

src/charactersheet/viewmodels/common/chat/chat_detail/index.js, src/charactersheet/viewmodels/common/chat/index.html, src/charactersheet/viewmodels/common/chat/index.js
- Fixes an issue where chat badges would not be cleared.
- Updates Chat VM to actually reload data when room changes (after webpack refactor).
Fixes #1613 
None
None
=> Fixes issue with chat badges not updating

src/charactersheet/viewmodels/dm/encounter/index.js, src/charactersheet/viewmodels/dm/encounter_add_edit_modal/index.js, src/charactersheet/viewmodels/dm/encounter_detail/index.js
Fixes issue caused by deleting the last encounter that would make the encounter detail remain.
Fixes #1629
=> Delete last encounter fix

src/charactersheet/viewmodels/dm/encounter/index.js, src/charactersheet/viewmodels/dm/encounter_cell/index.js, src/charactersheet/viewmodels/dm/encounter_detail/index.js
Fixes issue that doesn't allow a newly imported DM to add an encounter.
Fixes #1628
=> Error after creating an encounter when a DM is imported

src/charactersheet/viewmodels/common/player_image/index.html, src/charactersheet/viewmodels/common/player_image/index.js
- Profile Image no longer saves until done button is clicked. 
Fixes #1612 
None
None
=> Fixes issue with Player Profile Image by delaying save until done button clicked

src/charactersheet/viewmodels/common/root/index.html, src/charactersheet/viewmodels/common/root/index.js, webpack.dev.js, webpack.prod.js, webpack.test.js
Adds dynamic link to app homepage
Fixes #1637
=> Ac link fix

src/charactersheet/viewmodels/common/root/index.js
Fixes issue with Purge using `window` which is invalid after webpack .
Fixes #1632 
None 
None
=> Fixes issue with Purge entries not working with Webpack

src/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section/index.html
Fixes error that pops up when you close a new modal in map encounter sections.
=> Another map fix

src/charactersheet/viewmodels/common/characters/index.html, src/charactersheet/viewmodels/common/characters/index.js, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.js
Fixes issue with modal backdrop not disappearing when deleting the last character.
=> Characters modal fix

src/charactersheet/viewmodels/common/root/index.html
- Fixes support page link
- None logged
None
None
=> Fixes support page link.

src/charactersheet/viewmodels/common/root/index.html, src/charactersheet/viewmodels/common/wizard/index.js
- Fixes issue with the data from the previous step not being cleared.
- None logged
- None
- N/A
=> Wizard fix

src/charactersheet/viewmodels/dm/encounter_cell/index.js
- Supposed fix for issue happening on nightly with encounter cells reloading with null data.
None logged
None
None
=> Fixes issue with Encounter Cells reloading with null and causing error.

src/charactersheet/viewmodels/dm/encounter/index.js
- Encounters are now given a default name.
None logged
None
NOne
=> Blank encounters are now given a default title

src/charactersheet/init.js
- Makes for easy debugging in prod
None 
None
None
=> Adds the Persistence Service to the Window.

src/charactersheet/viewmodels/common/notes/index.html, src/charactersheet/viewmodels/common/notes/index.js, src/style/site.css
Adds placeholder when deleting last note
=> Fix UX for deleting last note

src/charactersheet/viewmodels/dm/encounter/index.js, src/charactersheet/viewmodels/dm/encounter_cell/index.js, src/charactersheet/viewmodels/dm/encounter_detail/index.js, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/notes_section/index.js
- When encounters are deleted they now delete their associated encounter sections.
Fixes #1659 
None
None
=> Deleting encounters now delete their associated sections.

src/style/site.css
- App now stretches the entire screen for large devices.
Fixes #1670
=> Changes app width to be 100% to accomodate for bigger devices.

src/charactersheet/services/character/status_service_components/healthiness_component.js, src/charactersheet/utilities/fixtures.js, src/charactersheet/utilities/notifications.js, src/charactersheet/viewmodels/character/stats/index.html, src/charactersheet/viewmodels/character/stats/index.js
Fix statusline hitdice
Fixes #1509
=> Fix statusline hitdice

src/charactersheet/viewmodels/character/stats/index.js
Fixes an issue where the character is stable toastr is not firing at page load.
Fixes #1681
=> Call player is stable handler at load

src/charactersheet/viewmodels/common/character_picker/index.html, src/charactersheet/viewmodels/common/character_picker/index.js, src/charactersheet/viewmodels/common/characters/index.html, src/style/site.css
- Added delete button in main character picker. 
- Spaced columns to optimize mobile. 
- Updated character picker modal with similar enhancements.
Fixes #1672
=> Add delete button to Character Picker Page

src/charactersheet/viewmodels/common/notes/index.js, test/viewmodels/test_notes.js
Add selected note logic
Fixes #1664
=> Add selected note logic

src/charactersheet/models/common/item.js, src/charactersheet/models/common/magic_item.js, src/charactersheet/models/common/weapon.js, src/charactersheet/models/dm/encounter_sections/encounter_armor.js, src/charactersheet/models/dm/encounter_sections/encounter_weapon.js, src/charactersheet/viewmodels/character/items/index.html, src/charactersheet/viewmodels/character/magic_items/index.html, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/player_text_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/index.html, test/models/dm/encounter_sections/test_encounter_armor.js, test/models/dm/encounter_sections/test_encounter_weapon.js
- Improved styling of various sections on mobile.
Fixes #1477 
- None
=> Various updates to dm encounter sections mobile UI.

.babelrc, CHANGELOG.md, package.json, webpack.common.js
- Adds babel support for transpiling to old versions of ES5 to support older browsers.
=> Adds webpack -> babel transpiling for old browsers

package-lock.json
- Adds new package-lock with new version and deps.
None
=> Adds new package lock

src/charactersheet/viewmodels/dm/encounter_sections/player_text_section/index.html
- Fixes styling in player text
Fixes #1688
=> Fixes styling with player text.

src/charactersheet/viewmodels/common/wizard/index.js
- Wizard steps can now be made to be un-ready.
- Ability Scores can now enforce a value in the wizard.
None logged
None
None
=> Wizard steps can now be made un-ready.

src/charactersheet/viewmodels/common/root/index.html
=> Adds back login button when not in the main app

.babelrc, karma.conf.js, webpack.common.js
- Removed double babel compilation.
- Removed redundant settings.
- Fixed exclude regex for tests/node_modules
- Faulty regex caused redundant babel compilation
Run Results
-----------
Without Changes:
real	1m49.142s
user	1m43.386s
sys 	 0m4.617s
With Changes:
real	1m13.272s
user	1m15.259s
sys 	 0m2.947s
None logged
None
None
=> Speeds up test running by ~30%.

src/bin/knockout-jquery-autocomplete.js
- Fixes an issue with Autocomplete being slow after multiple uses.
None 
None
None
=> Fixes an issue with Autocomplete being slow after multiple uses.

src/charactersheet/services/character/status_service_components/healthiness_component.js
Fix death save index error
Fixes #1715
=> Fix death save index error

package.json, src/charactersheet/models/dm/encounter_sections/monster.js, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.js
- Monster saving now filters by the name of the score to prevent accidental overrides of data...
Fixes #1713 
None
None
=> Fixes issue with Monster Ability Scores not saving properly

src/bin/knockout-jquery-autocomplete.js, src/charactersheet/viewmodels/character/feats/index.html, src/charactersheet/viewmodels/character/features/index.html, src/charactersheet/viewmodels/character/proficiencies/index.html, src/charactersheet/viewmodels/character/traits/index.html, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.html, src/style/site.css
Fixes autocomplete scrolling issue
Fixes autocomplete not working anymore issue
=> Fix autocomplete

src/charactersheet/viewmodels/character/profile/index.html, src/charactersheet/viewmodels/character/root/index.html
=> Add id tags for selenium

CHANGELOG.md
=> Updates changelog for hotfix.

src/charactersheet/viewmodels/character/appearance/index.html, src/charactersheet/viewmodels/character/feat_traits/index.html, src/charactersheet/viewmodels/character/feats/index.html, src/charactersheet/viewmodels/character/features/index.html, src/charactersheet/viewmodels/character/root/index.html, src/charactersheet/viewmodels/character/traits/index.html, src/charactersheet/viewmodels/common/root/index.html, src/charactersheet/viewmodels/dm/dmscreen/index.html, src/charactersheet/viewmodels/dm/overview/index.html, src/charactersheet/viewmodels/dm/root/index.html
=> Add ids for selenium

src/charactersheet/viewmodels/character/spell_stats/index.html
=> Adds ids to spell stats

src/charactersheet/components/nested-list.js, src/charactersheet/viewmodels/common/chat/chat_cell/index.js, src/charactersheet/viewmodels/common/chat/chat_detail/index.js, src/charactersheet/viewmodels/common/chat/chat_log_chat_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_image_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_read_aloud_item/index.js
Fixes dropbox profile pictures not rendering in chat section.
Fixes #1740
=> Fixes dropbox profile pictures not rendering in chat section.

src/charactersheet/viewmodels/character/items/index.html, src/charactersheet/viewmodels/character/items/index.js, test/viewmodels/test_items.js
Fixes issue with sorting the inventory and fixes mobile view of table.
Fixes #1734
=> Inventory Sort error

src/charactersheet/models/common/treasure.js, test/models/test_treasure.js, test/viewmodels/test_treasure.js
Fix worth in gold calculation
Fixes #1746
=> Fix worth in gold calculation

src/charactersheet/viewmodels/character/armor/index.html, src/charactersheet/viewmodels/character/armor/index.js, test/viewmodels/test_armor.js
Adds sorting to equipped and AC column of armor and fixes mobile look.
Fixes #1744
=> Armor sorting on equipped

src/charactersheet/viewmodels/common/root/index.html, src/charactersheet/viewmodels/common/root/index.js, webpack.dev.js, webpack.prod.js, webpack.test.js
Fix copyright year
Fixes #1759
=> Fix copyright year

src/charactersheet/models/character/health.js, src/charactersheet/viewmodels/character/stats/index.html, src/style/site.css, test/viewmodels/test_stats.js
Updates css for centering text on hp progress bar. Adds label for temp hp on progress bar.
=> Update HP label

src/charactersheet/viewmodels/common/root/index.html
=> Add navbar icons

src/charactersheet/services/character/sync/character_card_fields.js, src/charactersheet/services/dm/sync/dm_card_fields.js, src/charactersheet/viewmodels/common/chat/chat_log_chat_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_image_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_read_aloud_item/index.js, src/charactersheet/viewmodels/common/chat/chat_modal/index.js, src/charactersheet/viewmodels/dm/party/index.js, src/charactersheet/viewmodels/dm/player_push_modal/index.js
Fixed more locations where dropbox images were not rendering or failing to render.
=> More dropbox image fixes

package-lock.json, package.json, src/bin/knockout-validation.js, src/charactersheet/init.js, src/charactersheet/viewmodels/character/features/index.html, src/charactersheet/viewmodels/character/features/index.js, src/charactersheet/viewmodels/character/features/validation.js
- Using the new validation, we can apply form validation to all modals and other places.
- The Features has been updated to have an example of how to use this new validation including a new validation.js with the common rules for add/edit modals.
- There is still work to be done in the handling of updates and submissions but this should get us close enough for now.
=> Adds a new validation framework and an example in Features.

src/charactersheet/viewmodels/common/root/index.js, webpack.test.js
No idea how this got turned off, but it's back now.
NOTE: These are heavy maps.
=> Enables SourceMaps in Test Mode.

package.json, src/charactersheet/viewmodels/common/root/index.js
=> Fixes tab changing bug

src/charactersheet/models/common/spell.js, src/charactersheet/viewmodels/character/magic_items/index.js, src/charactersheet/viewmodels/character/spells/index.html, src/charactersheet/viewmodels/character/spells/index.js, test/viewmodels/test_spells.js
Fixes spell damage label not updating
=> Fixes issue with spell damage.

src/charactersheet/models/common/magic_item.js, src/charactersheet/viewmodels/character/magic_items/index.js
Updates magic items to include used charges when none is provided by the autofill data.
Fixes #1839 
Fixes #1840
=> Updates magic items charges

src/charactersheet/models/common/spell.js
Fixes issue with adding cantrips
=> Updates validation for spells to allow cantrips to be added

src/charactersheet/models/common/item.js, src/charactersheet/models/common/magic_item.js, src/charactersheet/models/common/weapon.js, src/charactersheet/viewmodels/character/items/index.html, src/charactersheet/viewmodels/character/items/index.js, src/charactersheet/viewmodels/character/magic_items/index.html, src/charactersheet/viewmodels/character/magic_items/index.js, src/charactersheet/viewmodels/character/weapons/index.html, src/charactersheet/viewmodels/character/weapons/index.js, src/charactersheet/viewmodels/dm/campaign_maps_and_images/index.js
Adds validations to items, magic items, and weapons
=> Adds form validation to items, magic items, and weapons.

src/charactersheet/components/preview-edit.js, src/charactersheet/models/character/other_stats.js, src/charactersheet/models/character/profile.js, src/charactersheet/models/common/wealth.js, src/charactersheet/viewmodels/character/background/index.html, src/charactersheet/viewmodels/character/background/index.js, src/charactersheet/viewmodels/character/other_stats/index.html, src/charactersheet/viewmodels/character/other_stats/index.js, src/charactersheet/viewmodels/character/profile/index.html, src/charactersheet/viewmodels/character/profile/index.js, src/charactersheet/viewmodels/character/spells/index.html, src/charactersheet/viewmodels/character/wealth/index.html, src/charactersheet/viewmodels/character/wealth/index.js, src/style/site.css
Adds preview edit to other stats and wealth.
Adds cancel button to preview edit.
Adds placeholder text for blank or null values in preview edit.
Adds Done button back to spells preview
=> Validation for wealth, other stats, and other fixes

src/charactersheet/utilities/convenience.js
=> Fix npc quotes

src/app.js, src/charactersheet/viewmodels/common/root/index.js, src/index.html
A loading screen now appears before XMPP connections are established.
None logged
N/A
=> Adds Application-wide Loading Screen

src/app.js
Fixes an issue where the profile dropdown doesn't work.
Fixes #1856 
N/A
=> Fixes broken dropdown

src/charactersheet/components/preview-edit.js, src/charactersheet/init.js, src/charactersheet/models/common/armor.js, src/charactersheet/models/common/item.js, src/charactersheet/models/common/magic_item.js, src/charactersheet/models/common/spell.js, src/charactersheet/models/common/weapon.js, src/charactersheet/models/dm/encounter_sections/encounter_armor.js, src/charactersheet/models/dm/encounter_sections/encounter_item.js, src/charactersheet/models/dm/encounter_sections/encounter_magic_item.js, src/charactersheet/models/dm/encounter_sections/encounter_weapon.js, src/charactersheet/models/dm/encounter_sections/monster_ability_score.js, src/charactersheet/services/character/status_service_components/healthiness_component.js, src/charactersheet/viewmodels/character/armor/index.html, src/charactersheet/viewmodels/character/items/index.html, src/charactersheet/viewmodels/character/magic_items/index.html, src/charactersheet/viewmodels/character/magic_items/index.js, src/charactersheet/viewmodels/character/spells/index.html, src/charactersheet/viewmodels/character/spells/index.js, src/charactersheet/viewmodels/character/stats/index.js, src/charactersheet/viewmodels/character/weapons/index.html, src/charactersheet/viewmodels/common/player_image/index.js, src/charactersheet/viewmodels/dm/campaign_maps_and_images/index.js, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.js
Various core bug updates:
- Preview edit form can not be saved for inspiration change.
- Fixes bug where inspiration doesn't update for character change
- Updates spells, items, magic items, weapons, armor descriptions to use markdown
- Update death saves to show when in negative hp.
- Updates modals to clear the image before they load another modal
- Fixes an issue where environments didn't update when encounters changed
Fixes #1873 
Fixes #1871
Fixes #1802
Fixes #1876
Fixes #1872
Fixes #1803
Fixes #1819
Fixes #1874
=> Various core bug updates:

src/charactersheet/components/image-picker.js, src/charactersheet/services/common/account/messaging/node_service.js, src/charactersheet/viewmodels/common/chat/chat_modal/index.js
Fixed an issue where creating multiple private chats over time resulted in the additional, incorrect users being added to a private chat.
- Also fixes issue where subscriptions might not be sent to other party members.
Addresses part of #1779
N/A
N/A
=> Fixes an issue where the chat would invite the wrong members.

src/charactersheet/models/common/character.js, src/charactersheet/viewmodels/common/wizard/index.html, src/charactersheet/viewmodels/common/wizard/index.js, src/charactersheet/viewmodels/common/wizard/steps/index.js, src/charactersheet/viewmodels/common/wizard/steps/wizard_file_import_error_step/index.html, src/charactersheet/viewmodels/common/wizard/steps/wizard_file_import_error_step/index.js, src/charactersheet/viewmodels/common/wizard/steps/wizard_intro_step/index.html, src/charactersheet/viewmodels/common/wizard/steps/wizard_intro_step/index.js
- Refactors importing to use api import
- Adds error page for handling import failures
=> Adds back the ability to import a file from Dropbox or from a local file.

src/charactersheet/services/common/sync/card_service.js, src/charactersheet/viewmodels/common/player_image/index.js
Players image updates could run into race conditions when updating a pcard.
I have made it more synchronous by using async/await.
=> Updates image notifications to be more synchronous.

src/charactersheet/viewmodels/common/chat/chat_detail/index.html, src/charactersheet/viewmodels/common/chat/chat_detail/index.js
The convenience function I made to make it easier to access the chatRoom was updating **after** it was being needed... This function was added to lessen the pain of the eventual refactor, but caused more issues than it solved, so I just removed it.
N/A
N/A
N/A
=> Fixes issue with chat switching.

src/charactersheet/models/dm/encounter_sections/environment.js, src/charactersheet/models/dm/image.js, src/charactersheet/viewmodels/common/party_manager/index.html, src/charactersheet/viewmodels/common/party_manager/index.js, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/notes_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/player_text_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/index.js
- Fix encounter error that fetch sections that don't exist
=> Fix encounter error that fetch sections that don't exist

src/charactersheet/services/character/armor_class_service.js, src/charactersheet/viewmodels/dm/encounter_detail/index.js
- AC was not including dex because the wrong field was being used.
=> Fixes an issue with ac not including dex.

src/charactersheet/models/character/skill.js, src/charactersheet/services/character/armor_class_service.js, src/charactersheet/viewmodels/character/skills/index.js, src/charactersheet/viewmodels/dm/encounter_detail/index.js
- Skills were not updating correctly due to wrong signal
- Potentially fixes `NaN` issue
=> Skill update fix

src/charactersheet/services/character/status_service_components/healthiness_component.js, src/charactersheet/viewmodels/character/stats/index.js, src/charactersheet/viewmodels/common/root/index.html
- Disables export button.
- Adds more async/await
=> Fixes calculation issues with health status.

src/charactersheet/init.js
The animations are back in town. *The animations are back in town.*
Bootstrap animations are now working in all cases.
Fixes #1875 
N/A
N/A
=> Adds back bootstrap animations.

src/charactersheet/services/character/sync/character_card_fields.js, src/charactersheet/viewmodels/common/chat/chat_log_image_item/index.js, src/charactersheet/viewmodels/common/root/index.html
- Fixes issue where hit dice don't calculate correctly for the character pcard
- Centers footer icons
=> Fixes hit dice in character pcard

src/charactersheet/viewmodels/character/armor/index.html, src/charactersheet/viewmodels/character/skills/index.html, src/charactersheet/viewmodels/character/skills/index.js
- Adds back ability scores to add skills modal.
- Adds required star to stealth field in armor
Fixes #1907 
Fixes #1906
=> Fixes small bugs found post launch

src/charactersheet/viewmodels/dm/dmscreen/index.html
Small typo fix: _actor -> factor_
=> DM screen typo fix

CHANGELOG.md, package.json, src/charactersheet/viewmodels/character/armor/index.html, src/charactersheet/viewmodels/character/skills/index.html, src/charactersheet/viewmodels/character/skills/index.js, src/charactersheet/viewmodels/dm/dmscreen/index.html
=> v2.0.1 Hotfix

CHANGELOG.md, package.json
=> Updates changelog and package json for new version

src/bin/knockout-binding-contenteditable.js, src/charactersheet/models/character/profile.js, src/charactersheet/models/common/core.js, src/charactersheet/models/common/player_image.js, src/charactersheet/models/dm/campaign.js, src/charactersheet/viewmodels/common/player_name/index.html
Updates dependencys surrounding core to allow the characters and games list to fetch correctly.
Fixes #1916
=> Fixes caching issue with fetching cores

src/charactersheet/models/common/spell.js, src/charactersheet/viewmodels/character/spells/index.html
- Type and Duration for spells are required
None loggged
N/A
N/A
=> Adds requirements to fields required by the API.

src/charactersheet/services/common/hotkeys_service.js
Fixes issue with tabs switching when typing numbers in the playerName input.
=> Fixes Jim bug

src/charactersheet/viewmodels/character/armor/index.js, src/charactersheet/viewmodels/character/items/index.js, src/charactersheet/viewmodels/character/magic_items/index.js, src/charactersheet/viewmodels/character/weapons/index.js
- Weapons, Armors, Items, and Magic Items now more accurately handle for decimal values and approximate weights.
None logged.
N/A
N/A
=> Adds handling for approximate weights

src/charactersheet/models/common/image.js, src/charactersheet/models/dm/encounter_sections/environment.js, src/charactersheet/models/dm/encounter_sections/monster.js, src/charactersheet/models/dm/encounter_sections/npc.js, src/charactersheet/models/dm/encounter_sections/player_text.js, src/charactersheet/models/dm/encounter_sections/point_of_interest.js, src/charactersheet/models/dm/image.js, src/charactersheet/viewmodels/common/chat/chat_log_poi_item/index.html, src/charactersheet/viewmodels/common/chat/chat_log_poi_item/index.js, src/charactersheet/viewmodels/dm/campaign_maps_and_images/index.html, src/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/player_text_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/player_text_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/index.js, src/charactersheet/viewmodels/dm/player_push_modal/index.html, src/charactersheet/viewmodels/dm/player_push_modal/index.js, src/style/site.css
Npc, maps and images, point of interest, and monster have received the following ability:
- Send/exhibit their content
- Have a special field for player text (used when sent in chat)
- Added image field
- Rendered image
- Adds indicator that shows which field is sent to players
Fixes #1932 
Fixes #1930
=> Encounter section enhancements

webpack.prod.js
Add a conditional to create source maps if environment is test.
=> Add webpack nightly config

src/charactersheet/utilities/json_payload.js, src/charactersheet/viewmodels/common/chat/chat_log_poi_item/index.js, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.js
Hopefully fixes some issue with exhibits and sending content
=> Minor fixes with exhibit

src/charactersheet/settings.js, src/charactersheet/viewmodels/dm/encounter_sections/trap_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/trap_section/index.js
- Traps now prepopulate SRD trap data.
None logged
N/A
N/A
=> Adds prepop to traps section.

CHANGELOG.md, package-lock.json, package.json
=> Adds changelog and updates version name.

src/charactersheet/models/common/note.js, src/charactersheet/utilities/fixtures.js, src/charactersheet/viewmodels/common/chat/chat_log_chat_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_image_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_poi_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_read_aloud_item/index.js
- Adds back functionality to save "DM sent" content to notes
- Adds convenience functions to Notes model.
=> Adds convenience method to notes and fixes saving to note from chat.

src/charactersheet/models/common/note.js, src/charactersheet/viewmodels/common/chat/chat_log_chat_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_image_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_poi_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_read_aloud_item/index.js
- Maybe fixes issues with saving notes
=> Minor fixes to notes model

src/charactersheet/models/common/note.js, src/charactersheet/viewmodels/character/weapons/index.html, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/index.html
- Uses the correct fields. Ft. @Sonictherocketman
=> Save to chat fixes

package-lock.json, package.json, webpack.dev.js
- jQuery security vulnerability addressed.
- Circular dep plugin is removed.
N/A
N/A
N/A
=> Fixes secvuls and turns off noisy plugins

src/charactersheet/models/common/armor.js, src/charactersheet/models/common/item.js, src/charactersheet/models/common/magic_item.js, src/charactersheet/models/common/spell.js, src/charactersheet/models/common/weapon.js, src/charactersheet/models/dm/encounter_sections/encounter_armor.js, src/charactersheet/models/dm/encounter_sections/encounter_item.js, src/charactersheet/models/dm/encounter_sections/encounter_magic_item.js, src/charactersheet/models/dm/encounter_sections/encounter_weapon.js, src/charactersheet/viewmodels/character/armor/index.html, src/charactersheet/viewmodels/character/feats/index.html, src/charactersheet/viewmodels/character/features/index.html, src/charactersheet/viewmodels/character/items/index.html, src/charactersheet/viewmodels/character/magic_items/index.html, src/charactersheet/viewmodels/character/proficiencies/index.html, src/charactersheet/viewmodels/character/spells/index.html, src/charactersheet/viewmodels/character/weapons/index.html, src/charactersheet/viewmodels/common/chat/chat_log_poi_item/index.js, src/charactersheet/viewmodels/common/chat/chat_log_read_aloud_item/index.js, src/charactersheet/viewmodels/common/notes/index.html, src/charactersheet/viewmodels/dm/campaign_maps_and_images/index.html, src/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/player_text_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/trap_section/index.html
- Remove regex that edits the markdow description
- Adds to every description textbox a note that says the field has markdown enabled.
- Some save from chat fixes.
- Only notes
=> Looks into markdown issues

src/charactersheet/viewmodels/character/saving_throws/index.js
- Subscribes to the correct notification for updating saving throws.
=> Subscribes to the correct notification for updating saving throws.

CHANGELOG.md, package-lock.json, package.json
=> Updates changelog v2.2.0

src/charactersheet/viewmodels/common/character_picker/index.html
- Shows an alert to the user to alert them (on the character/games picker only) that they could try out the new reskinned version of AC.
- This is blocked by the reskin actually launching.
N/A
N/A
=> Adds an alert to let users know they can check out the new beta version.

src/charactersheet/viewmodels/character/skills/form.js
=> Fixes issue where skill add form did not resize its container

src/charactersheet/viewmodels/character/spells/index.js
=> Fixes spell updates

src/charactersheet/viewmodels/character/armor/form.html, src/charactersheet/viewmodels/character/background/form.html, src/charactersheet/viewmodels/character/feats/form.html, src/charactersheet/viewmodels/character/features/form.html, src/charactersheet/viewmodels/character/items/form.html, src/charactersheet/viewmodels/character/magic_items/form.html, src/charactersheet/viewmodels/character/proficiencies/form.html, src/charactersheet/viewmodels/character/spells/form.html, src/charactersheet/viewmodels/character/traits/form.html, src/charactersheet/viewmodels/character/weapons/form.html
=> Removes incorrect validation on description and other textarea fields

src/charactersheet/viewmodels/character/spells/index.html
=> Fixes erroneous style attribute tags

src/charactersheet/viewmodels/abstract/tabular-view-model.js, src/charactersheet/viewmodels/character/feats/index.html, src/charactersheet/viewmodels/character/features/index.html, src/charactersheet/viewmodels/character/tracker/index.html, src/charactersheet/viewmodels/character/tracker/index.js, src/charactersheet/viewmodels/character/traits/index.html, src/style/site.css
Removes unneeded function from abstract tabular class.
=> Adds tracked description to Feature/Feat/Trait views. 

src/charactersheet/viewmodels/character/tracker/index.html, src/charactersheet/viewmodels/character/wealth/view.html, src/charactersheet/viewmodels/character/weapons/form.html
=> Fixes mismatched quotes

src/style/site.css
=> Fixes toaster position

src/charactersheet/viewmodels/common/root/index.html
- Adds beta notice to the character sheet.
None logged
N/A
=> Adds beta notice to character page 

src/charactersheet/models/character/health.js, src/charactersheet/services/character/status_service_components/healthiness_component.js, src/charactersheet/viewmodels/character/stats/deathsave.js, src/charactersheet/viewmodels/character/stats/form.js, src/charactersheet/viewmodels/character/stats/health.js, src/charactersheet/viewmodels/character/stats/view.js
=> Corrects dying

src/charactersheet/components/form-tracked-component.js
Fixes issue where tracked max field was not validated
=> Adds validation constraints to tracked

src/style/site.css
=> Minor fix to make saving throws larger than 9 more readable.

src/style/site.css
- Fixes an issue with the modal CSS in Safari.
None logged
N/A
N/A
=> Fixes modal css in safari

src/charactersheet/viewmodels/character/root/index.html, src/charactersheet/viewmodels/common/root/index.html, src/charactersheet/viewmodels/dm/root/index.html, src/style/site.css
- Removes collaboration tools from DM and Player
=> Removes Collab tools tabs

webpack.prod.js
This fix is not suitable for production. It is mearly here to get
nightly up and running again.
None logged
N/A
It loads at all.
=> Hotfixes an issue caused by babel uglification.

src/style/site.css
This is the same as the modals fix
None logged
None
=> Fixes select2 dropdowns in Safari

src/style/site.css
Fixes coin display issue on Firefox.
Fixes #2011 
N/A
N/A
=> Fixes display of coin fields on Firefox.

src/charactersheet/components/form-tracked-component.js, src/charactersheet/viewmodels/character/feats/index.html, src/charactersheet/viewmodels/character/features/index.html, src/charactersheet/viewmodels/character/skills/form.html, src/charactersheet/viewmodels/character/skills/view.html, src/charactersheet/viewmodels/character/spells/form.html, src/charactersheet/viewmodels/character/spells/index.html, src/charactersheet/viewmodels/character/traits/index.html
We have successfully moved from two deprecated platforms onto one! #progress
I also fixed an issue with the renaming from a previous commit
Fixes #1179 
N/A
N/A
=> Removes all glyphicons and replaces them with font-awesome.

src/charactersheet/viewmodels/common/wizard/steps/wizard_profile_step/index.js
We forgot to migrate a field name all those years ago. 
Fixes #2018 
N/A
N/A
=> Fixes issue where data repository item quantities did not carry over into generated character.

src/style/site.css
Fixes stretching of environment images for encounters.
N/A
N/A
=> Fixes streched environment images

src/charactersheet/viewmodels/character/features/index.html
Feature names are scrunched up in the current version. This gives them more space.
N/A
N/A
=> Fixes the column layout for the feature table.

src/charactersheet/viewmodels/common/root/index.html
=> Removes LLC from the name

src/charactersheet/viewmodels/dm/dmscreen/index.html
Adds encumbrance rules to the DM screen.
Fixes #2063
N/A
=> Adds encumbrance rules to the DM screen.

src/style/site.css
Clickable things were also set to some weird settings which normally did nothing but also broke things sometimes.
N/A
N/A
N/A
=> Fixes Clickable Styling

src/charactersheet/viewmodels/common/patron_of_the_day/index.html, src/charactersheet/viewmodels/common/patron_of_the_day/index.js
=> Fixes an issue caused by updating DRF + Makes Patron of the Day name bigger

src/charactersheet/viewmodels/common/login/index.html, src/charactersheet/viewmodels/common/root/index.html
- Fixes issue where UI would wrap nav bar onto two rows if the username was long enough.
N/A
N/A
=> Fixes username to specific max size and removes AC brand name on small devices

src/charactersheet/models/dm/encounter_sections/monster.js, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/view.html
Monsters again show their ability score modifiers.
Fixes #2075 
N/A
=> Adds back the monster ability score modifiers

src/charactersheet/viewmodels/common/player_card/index.html, src/charactersheet/viewmodels/common/player_card/index.js
- Adds a new tooltip for players in the same party. It explains that party members with rings are members on Patreon.
N/A
N/A
=> A new tooltip explains the patron rings and points to Patreon.

package.json, src/charactersheet/viewmodels/common/party/index.html
- Bumps Version
- Fixes the fact that the party online/offline filter was shown when not connected to a party.
N/A
N/A
=> Feature/version bump + Small Fixes

src/charactersheet/viewmodels/common/root/index.html
App once again flows to edges on large devices
Fixes #2091 
N/A
=> Reverts past efforts at container improvements.

src/charactersheet/components/d20.photos-help.js, src/charactersheet/components/index.js, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/form.html, src/style/site.css
- Adds new d20.photos helper link to POIs and Environments.
N/A
N/A
=> Adds new d20.photos notice for DMs using POIs and Environments

src/charactersheet/models/character/companion.js, src/charactersheet/viewmodels/character/companions/form.js
HP is no longer hacky.
None logged
N/A
N/A
=> Companions no longer parse the old HP value and instead prefer the new maxHp field instead

src/charactersheet/viewmodels/common/party/index.html, src/charactersheet/viewmodels/common/player_card/index.css, src/charactersheet/viewmodels/common/player_card/index.html, src/charactersheet/viewmodels/common/player_card/index.js, src/style/site.css
- Resolves weird grid issues on party tab.
N/A
N/A
=> Fixes weirdnesses with party member cards in odd row arrangements. Flexbox ftw.

src/charactersheet/models/common/spell.js
Adds validation to material components. Apparently it didn't exist before.
N/A
N/A
N/A
=> Adds material component validation

src/charactersheet/components/compendium-help.js, src/charactersheet/components/index.js, src/charactersheet/viewmodels/character/armor/form.html, src/charactersheet/viewmodels/character/companions/form.html, src/charactersheet/viewmodels/character/feats/form.html, src/charactersheet/viewmodels/character/features/form.html, src/charactersheet/viewmodels/character/items/form.html, src/charactersheet/viewmodels/character/magic_items/form.html, src/charactersheet/viewmodels/character/proficiencies/form.html, src/charactersheet/viewmodels/character/spells/form.html, src/charactersheet/viewmodels/character/traits/form.html, src/charactersheet/viewmodels/character/weapons/form.html, src/charactersheet/viewmodels/common/root/index.html, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/trap_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/components/armor.form.html, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/components/item.form.html, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/components/magic-item.form.html, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/components/weapon.form.html
- Adds compendium link to footer
- Adds new compendium autofill helper component
- Adds new component to all autofilling add forms
N/A
N/A
=> Adds Links & Add Form Helper to Compendium 

src/charactersheet/models/common/image_media.js, src/charactersheet/models/common/index.js, src/charactersheet/utilities/index.js, src/charactersheet/utilities/notifications.js, src/charactersheet/utilities/upload_file.js, src/charactersheet/viewmodels/character/character_portrait/form.html, src/charactersheet/viewmodels/common/index.js, src/charactersheet/viewmodels/common/media/index.html, src/charactersheet/viewmodels/common/media/index.js, src/charactersheet/viewmodels/common/media_manager/back.html, src/charactersheet/viewmodels/common/media_manager/back.js, src/charactersheet/viewmodels/common/media_manager/front.html, src/charactersheet/viewmodels/common/media_manager/front.js, src/charactersheet/viewmodels/common/media_manager/index.html, src/charactersheet/viewmodels/common/media_manager/index.js, src/charactersheet/viewmodels/dm/campaign_maps_and_images/form.html, src/charactersheet/viewmodels/dm/dm_portrait/form.html, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/form.html, src/style/site.css, webpack.common.js
- The new UI also allows users to select previously uploaded images from
the gallery of images.
- This new UI is aware of the Patreon limits for each user and warns
users if they are over the limit or not a patron.
- The new uploader is available in both the player tools and DM tools
for profile picures as well as for DMs on the encounter sections that
have images.
**REQUIRES API and CONFIG PR**
N/A
N/A
=> Adds the ability to upload images to the new ImageMedia Endpoint.

.circleci/config.yml
- This change adds a simple CI config that just attempts to build the project (in multiple Node environments)
- This should catch the most critical kinds of bugs. We don't have any tests anymore, so we cant run those.
- N/A
- N/A
- N/A
=> Adds Simple Circle CI Build Config

src/charactersheet/viewmodels/common/media/index.html, src/charactersheet/viewmodels/common/media/index.js, src/charactersheet/viewmodels/common/media_manager/front.js
- Counts now change when uploads complete.
- Standardized image height.
- Picker now resets after a short delay.
- Images now appear in picker after upload.
N/A
N/A
N/A
=> Addresses Feature Feedback.

src/charactersheet/models/dm/encounter_sections/environment.js, src/charactersheet/models/dm/encounter_sections/npc.js, src/charactersheet/models/dm/encounter_sections/point_of_interest.js, src/charactersheet/models/dm/image.js, src/charactersheet/viewmodels/dm/campaign_maps_and_images/view.html, src/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section/view.html, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/view.html, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/view.html
Fixes issues with Dropbox image rendering in DM Tools. Also removes unused method that was not purged with the others of its kind.
Fixes #2115 
N/A
N/A
=> Fixes Dropbox Image Rendering

src/charactersheet/components/index.js, src/charactersheet/components/mini-health-input.js, src/charactersheet/viewmodels/character/companions/index.html, src/charactersheet/viewmodels/character/companions/index.js
- adds component to add/subtract health
- updates companions tab to use new component
=> Adds mini health input to companions

src/charactersheet/models/common/wealth.js, src/charactersheet/viewmodels/character/wealth/view.html, src/charactersheet/viewmodels/character/wealth/view.js
Adds ability to quickly earn coin, not by adventuring, but by entering a number value into a field, and allowing the application to do the math for you.
Manual math when earning gold.
=> adds quick earn feature to wealth

package-lock.json
Yjs logging upgrade to fix logging in that module.
N/A
N/A
N/A
=> Fixes deploy issues with dep logging

src/charactersheet/components/nested-list/cell.html, src/charactersheet/components/nested-list/cell.js, src/charactersheet/components/nested-list/index.html
This issue would result in undesired behaviour on mobile devices and a kinda annoying bug on laptops and desktops.
N/A
N/A
N/A
=> Fixes an issue where selecting the enounter-disclosure indicator would select the encounter.

src/charactersheet/viewmodels/dm/dm_portrait/index.html, src/charactersheet/viewmodels/dm/dm_portrait/index.js
I have no idea if this is a good idea, but it was so trivial I had to try it. What do we think?
N/A
N/A
=> Adds the ability for the DM to hide their campaign header.

src/charactersheet/viewmodels/common/wizard/index.html, src/charactersheet/viewmodels/common/wizard/index.js
New button in Wizard for characters generates random names 
N/A
N/A
=> Adds the ability to generate random character names

src/charactersheet/viewmodels/common/wizard/index.js
The Character Creation Wizard now automatically prepopulates any class features for the selected character class that are granted at or below the character's level.
Depends on linked backend change.
N/A
N/A
N/A
=> The Wizard now Automatically Populates Class Features

src/charactersheet/models/common/character.js, src/charactersheet/settings.js, src/index.html, webpack.common.js
=> Finally removes all references to Dropbox code which sometimes causes UI crashes.

src/charactersheet/components/flip-card/index.js, src/charactersheet/models/common/core.js, src/charactersheet/viewmodels/character/character_portrait/view.html, src/charactersheet/viewmodels/common/character_picker/index.html, src/charactersheet/viewmodels/common/character_picker/index.js, src/charactersheet/viewmodels/common/characters/index.html, src/charactersheet/viewmodels/common/characters/index.js, src/charactersheet/viewmodels/dm/dm_portrait/view.html, src/style/site.css
- Improves the UI for the core switcher and core select screens
- Adds the ability to favorite cores which puts them at the top of the list
This PR requires a matching backend change PR.
N/A
N/A
=> Adds Ability to Favorite Cores + UI Improvements

src/charactersheet/viewmodels/common/elaboration/index.js, src/charactersheet/viewmodels/common/wizard/index.html, src/charactersheet/viewmodels/common/wizard/index.js
- Re-orders fields in character creation wizard.
- Adds the ability for players to use GPT to aid with character creation. Players are required to enter a Name, Class, and Race and can provide most other fields to GPT which will take them into account for creating their character personality, ideals, flaws, bonds, and backstory.
- Backstory is included in the character sheet as a note.
- Users are asked to confirm their choices from GPT before those changes are applied to their character sheet.
This requires a pair PR on the backend.
N/A
N/A
=> Adds the ability for players to use GPT to help with Character Creation

src/charactersheet/viewmodels/common/root/index.html
=> Updates newsletter links

src/charactersheet/models/common/elaboration.js
GPT for DMs was broken this whole time...
NA
NA
NA
=> Fixes GPT Elaborations for DMs after refactor for players changed the schema.

src/charactersheet/viewmodels/common/elaboration/index.html
=> Allow GPT to reply with markdown for added glancability.

src/charactersheet/components/nested-list/cell.html, src/charactersheet/models/dm/encounter.js, src/charactersheet/viewmodels/abstract/tabular-view-model.js, src/charactersheet/viewmodels/dm/encounter/edit.html, src/charactersheet/viewmodels/dm/encounter/form.html, src/charactersheet/viewmodels/dm/encounter/view.html, src/charactersheet/viewmodels/dm/encounter/view.js, src/charactersheet/viewmodels/dm/encounter_detail/form.html, src/charactersheet/viewmodels/dm/encounter_detail/view.html, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/view.html, src/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/notes_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/notes_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/player_text_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/trap_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/index.html, src/style/site.css
The Encounters List is now Sortable by Name (and Completion). 
This PR requires the approval of Completing Encounters since it is based on it.
=> Adds Sorting to Encounters
