charactersheet/charactersheet/models/ability_scores.js, charactersheet/charactersheet/models/campaign.js, charactersheet/charactersheet/models/character.js, charactersheet/charactersheet/models/chat_message.js, charactersheet/charactersheet/models/health.js, charactersheet/charactersheet/models/hit_dice.js, charactersheet/charactersheet/models/profile.js, charactersheet/charactersheet/models/saving_throws.js, charactersheet/charactersheet/models/skill.js, charactersheet/charactersheet/models/spell_slot.js, charactersheet/charactersheet/utilities/persistence_service.js
By default, KO Computed Observables are evaluated when they are declared. This causes enormous strain on the app when searching for objects in the DB (since KO has to evaluate all observables and their dependencies as it goes, even if they aren't needed).
This fix changes all the model-layer computed observables to pureComputed observables which, [according the KO's docs][1], are not evaluated unless requested. This has the effect of speeding up the page load time by over 50x and other huge speedups.
> Pure computed observables, introduced in Knockout 3.2.0, provide performance and memory benefits over regular computed observables for most applications. This is because a pure computed observable doesn’t maintain subscriptions to its dependencies when it has no subscribers itself. This …
=> Fixes huge issue with KO Computed Observables.

charactersheet/charactersheet/models/spell.js, charactersheet/charactersheet/models/spell_stats.js, charactersheet/charactersheet/spells/app.js, charactersheet/charactersheet/spells/spells.tmpl.html
If a bonus spell damage has been input in the Spell Stats module, the column in the Damage column in the Spells table will now show: __1d4 + 1 [Spell Bonus: +2]__
If a spell bonus has not been set, it will just read: __1d4 + 1__
=> Spell Bonus in Spell table

charactersheet/charactersheet/equipment/app.js, charactersheet/charactersheet/equipment/equipment.tmpl.html
If there are items in the inventory, and they have a numerical weight, they will be summed and put next to the label on the column header. Currently, ignores values that are characters.
=> Added total weight label in inventory module

charactersheet/charactersheet/templates/spell_slots.tmpl.html
Spell slots can now be edited by clicking on the row. Fixing #303
=> Enabled spell slots edit modal.

charactersheet/charactersheet/viewmodels/profile.js, charactersheet/charactersheet/viewmodels/skills.js
Fixes #416, #418 
- Removes an unneeded jQuery $.each call.
- By resetting the profile object during `unload` the subscriptions
for that object will be GC'd.
=> Fixes issue where profile module doesn't clean up after itself.

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/armor.js, charactersheet/charactersheet/models/hit_dice_type.js, charactersheet/charactersheet/models/magic_item.js, charactersheet/charactersheet/models/spell.js, charactersheet/charactersheet/models/spell_stats.js, charactersheet/charactersheet/models/weapon.js, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/viewmodels/armor.js, charactersheet/charactersheet/viewmodels/items.js, charactersheet/charactersheet/viewmodels/weapons.js
New way to access static arrays and to create new static array.
If you need to access an existing static array, the format will be the following:
`
Fixtures.<model/viewmodel name>.<staticListName>
`
Example for getting weapon proficiency list: 
`
Fixtures.weapon.weaponProficiencyOptions
`
If you need to add new static list:
- If the model/viewmodel already exists, simply add it to that array within the main **_Fixtures_** arrays.
- If the model/viewmodel doesn't already exist, add a new one under the main **_Fixtures_** array.
Fixes #462
=> Removed all satic lists from viewmodels and models.

charactersheet/bin/tooltip_bind.js
The tooltip binding now checks if the current device has touch enabled, and if so does not enable tooltips. We might want to be more clever with this in the future (i.e. allow the binding to override and use the tooltips if given an option, etc) but this should be enough for now.
Fixes #627
None
None
**Desired Reviewer:** @tanyxp @jkrooskos
=> Turns off tooltips on touch devices

charactersheet/charactersheet/services/hotkeys_service.js
Hotkeys now work everywhere except **input** and **textareas**
Fixes #677
N/A
=> Fixed hotkeys not working on <a> tags

charactersheet/charactersheet/index.html
When in large size, the nav bar margins follow the 1-10-1 style of the content. When smaller, it goes edge-to-edge like the content.
Fixes #651
None
=> Navbar now follows page margins

charactersheet/charactersheet/index.html
Changes Image-Content ratios on large displays to 3-9 over 4-8. This prevents the content images from overwhelming the interface on large screens. Other sizes unaffected
None Logged.
None
=>  Changes Image-Content ratios on large displays to 3-9 over 4-8.

charactersheet/charactersheet/index.html, charactersheet/charactersheet/init.js, charactersheet/charactersheet/settings.js
- Extracts settings into external file.
- Fixes issue where certain models would import Persistence IDs and break import process. This would cause the illusion of data loss but the complete exported file would still have the preserved data.
Fixes #571 
Fixes #720 
None
None
=> Fixes data export/import

deploy.sh
Travis builds fail on `master` after new released because the tests are removed during the deploy process.
When a travis file is present, Travis builds and runs the tests. This removes the `.travis.yml` file when deploying the new releases.
None logged.
None
=> Fixes failing builds to master when pushing new releases.

charactersheet/charactersheet/components/plus-minus.js
When a value was manually entered for a damage/used value and then the stepper was called to incr/decr the value, it would be added as a string.
Turns out this was an issue with all of our steppers and it's fixed in the component.
Fixes #734 
None
=> Fixes Stepper math issue

charactersheet/charactersheet/utilities/fixtures.js
Fixed short rest message to display accurate message, i.e. what exactly was altered after the short rest.
#757
=> Fix short rest message

charactersheet/charactersheet/models/spell.js, charactersheet/charactersheet/templates/saving_throws.tmpl.html, charactersheet/charactersheet/templates/skills.tmpl.html, test/models/test_spell.js
Prevented page from refreshing due to enter key pressed
Fixes #771 
Apparently, browsers submit modals that have only __one__ input field on enter key press. Changed form attribute to not submit on enter key press.
=> Skills fix

charactersheet/bin/knockout-boostrap-collapse.js, charactersheet/charactersheet/index.html, charactersheet/charactersheet/templates/actions_toolbar.tmpl.html, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/actions_toolbar.js, charactersheet/charactersheet/viewmodels/root.js
- The binding requires an observable which determines whether or not the well is open
- The binding also has an optional callback parameter which is called when the open/close animation has finished.
- The Actions Toolbar now uses this binding.
- Fixes an issue where the actions init/load/unload calls were never made.
Fixes #602 
Supplants #780 
From the Commit Notes:
> During development there was an issue with activating the toolbar via signals and hotkeys. This was due to the fact that the Actions Toolbar was attempting to set the hotkeys during the load/init process. According to the debug logs it appeared that the call was being made but on a different object than the one used later in the process. 
> The actual issue turned out to be that the Actions Toolbar was appearing to call …
=> Adds HotKey for Toggling the Actions Toolbar

charactersheet/charactersheet/models/spell_slot.js, charactersheet/charactersheet/templates/spell_slots.tmpl.html, charactersheet/charactersheet/utilities/fixtures.js, charactersheet/charactersheet/viewmodels/spell_slots.js
- Adds an option for slots to reset on short rest. 
- Slots default to resetting on long rest.
None logged.
=> Spell slots can now be reset on short rest

charactersheet/charactersheet/templates/treasure.tmpl.html, charactersheet/site.css
- Even at the smallest end of large devices, all text can be read up to 3 digits and boxes do not overlap.
- Cleaned up unneeded columns and changed them to use col-offsets instead.
All other device sizes unchanged.
Fixes #782
=> Fixes treasure coin styling on small end of large device size.

charactersheet/charactersheet/viewmodels/characters.js, charactersheet/charactersheet/viewmodels/root.js
The following functionality was added to the unload process:
- Entries in any model table (excluding character) that contain a value for
characterId that is null or undefined are removed.
- Entries for any model table (excluding character) that contain a value for
characterId that is not present in the Character model table are removed.
This is a fairly crude, but effective method of cleaning out stray and null
entries. Ideas and suggestions for improvement welcome.
Fixes #744 
If anything this solidifies the use of the keyword `characterId` as the identifier of the character a model belongs to. Models are, of course, free to use any identifier, but they will not be automatically cleaned up.
=> Adds functionality to enforce data cleanup.

charactersheet/charactersheet/init.js, charactersheet/charactersheet/settings.js
- Adds list of data repos to fetch to the `Settings.js`
- During init, fetch each of the datasets in the list, and set them to values in the `DataRepository`
**Note:** I decided to add this to `settings.js` not `fixtures.js` because it isn't the data itself, but instead a setting of where to find it.
Fixes #835 
None
None
=> Genericises Data Loading Process.

charactersheet/charactersheet/templates/spells.tmpl.html
Set min to 0 for spell level in edit modal
Fixes #851
=> Set min to 0 for spell level in edit modal

charactersheet/charactersheet/templates/spells.tmpl.html
Added fields to spell modal to represent "isRitual" and "spellMaterialComponents".
Fixes #869 
Fixes #816 
Fixes #815 
In an attempt to save vertical space, I put the ritual checkbox next to the prepared checkbox. Let me know if you like this look. If not, I can stack them vertically. @adventurerscodex/core-developers
=> Spell UI update

charactersheet/bin/knockout-mapping-autoignore.js, charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/character/ability_scores.js, karma.conf.js
- Currently, fields that must be ignored, or included in model serialization must be explicitly specified in the KO Mapping fields. This leads to redundant specification since it can be implied that if a field should not be included, then it should be excluded. This adds a new extension to `ko.mapping` that automatically ignores any fields that aren't specified in the `mapping.include` list.
- Additional fields may be ignored explicitly.
- An example is implemented in the Ability Scores.
None logged.
None.
None.
=> Adds new autoignore to mapping.

charactersheet/charactersheet/models/common/weapon.js, charactersheet/charactersheet/templates/character/weapons.tmpl.html, test/models/test_weapon.js
Only show magical modifier badge on weapons widget if there is a modifier
Fixes #941
=> Only show magical modifier badge on weapons widget if there is a modifier

charactersheet/charactersheet/models/common/item.js, charactersheet/charactersheet/models/common/magic_item.js, charactersheet/charactersheet/templates/character/items.tmpl.html, charactersheet/charactersheet/templates/character/magic_items.tmpl.html, charactersheet/charactersheet/viewmodels/character/items.js
Cuts down on long descriptions. Below are how the short descriptions appear on devices. The column is hidden on sm and xs.
@adventurerscodex/core-developers Feedback on character limit appreciated.
Fixes #902 
**Large:**
**Medium:**
**Small:**
**Extra-small:**
=> Truncate characters in table column

charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/common/image.js, charactersheet/charactersheet/models/common/player_image.js, charactersheet/charactersheet/templates/character/player_image.tmpl.html, charactersheet/charactersheet/templates/common/settings.tmpl.html, charactersheet/charactersheet/viewmodels/character/character_root.js, charactersheet/charactersheet/viewmodels/character/player_image.js, charactersheet/charactersheet/viewmodels/character/profile_tab.js, charactersheet/site.css, test/models/test_image.js
Redesigns Player Image UI and Code. 
- Players can no longer save images by dragging them into the circle (this was
unfriendly to mobile to start anyway).
- Instead, players click/tap on the circle and are presented with a modal
prompting them to enter either (or both I guess) a remote image URL or their
gravatar email.
- This approach greatly simplifies the amount of code needed to store
actual images and improves the user's experience of using the app. Images
are huge in comparison with the campacity of LocalStorage (and later, sending
them over the wire might be too complex anyway).
- This also greatly simplifies the code needed for managing profile images.
- Since the original spot for the Player's Gravatar Email was in the Settings, and it was the only field. I have removed the …
=> Profile image redesign

charactersheet/charactersheet/templates/character/notes.tmpl.html
Add markdown link to notes widget
Fixes #992
=> Add markdown link to notes widget

charactersheet/charactersheet/viewmodels/character/player_image.js
- Old players will see their image persist as now the image link option is
selected by default.
- Fixes an issue where player images were not unloaded properly.
Fixes #993 
Fixes #995 
None
None
=> Sets image link as the default for players, and fixes bug.

charactersheet/charactersheet/components/markdown-edit-preview.js, charactersheet/charactersheet/templates/character/notes.tmpl.html
- Component now sets the default tab to preview if there is existing content.
Use the default to override this behavior. A lack of content will cause edit
to be selected.
Fixes #996 
None
None
=> Updates init logic in markdown-component.

charactersheet/charactersheet/components/nested-list.js, charactersheet/charactersheet/index.html, charactersheet/charactersheet/models/dm/encounter.js, charactersheet/charactersheet/models/dm/encounter_sections/notes_section.js, charactersheet/charactersheet/templates/dm/encounter.tmpl.html, charactersheet/charactersheet/viewmodels/dm/encounter.js, charactersheet/charactersheet/viewmodels/dm/encounter_cell.js, test/viewmodels/dm/test_encounter.js
- Encounters have now been divorced from their previous view-related
activities. Encounters are now displayed via EncounterCellViewModels which
map their underlying encounter model to a view cell.
- Doing this allows the encounter-list component to be generalized (as it
has been) into a nested-list component that can display any cell VM that
follows it's criteria.
Fixes #1047 
Fixes #1054
=> Fixes issue with reloading encounters.

charactersheet/bin/knockout-markdown.js
- Null values now cause empty strings to be passed to markdown parser.
- This would cause weird UI if bindings threw errors.
None Logged.
None
None
=> Fixes an issue where null text would break markdown parsing.

charactersheet/charactersheet/models/dm/encounter_sections/player_text_section.js
Changed default value for player-text visibility
Fixes #1068 
None
None
=> Read Aloud text is now on by default

charactersheet/charactersheet/viewmodels/character/profile.js
- When switching from a character to DM, the profile module should unsubscribe from notifications, since it missed 1, it would get notified to save data incorrectly. This caused errors when exporting DMs.
Fixes #1067 
We must be sure to unsubscribe from all notifications in the VM `unload` method.
None.
=> Fixes an issue where profiles would not unsubscribe from notifications

charactersheet/charactersheet/utilities/fixtures.js
Add magic damage types to options list for weapons
Fixes #1108
=> Add magic damage types to options list for weapons

charactersheet/charactersheet/components/nested-list.js, charactersheet/charactersheet/templates/character/notes.tmpl.html, charactersheet/charactersheet/templates/dm/encounter.tmpl.html, charactersheet/site.css
Convert trashcans and plus icons to font awesome for consistency.  This also converts the player character notes module icons too.
Fixes #1085
=> Convert trashcans and plus icons to font awesome for consistency

charactersheet/charactersheet/templates/character/other_stats.tmpl.html
Remove min from proficiency bonus adjustment element
Fixes #1138
=> Remove min from proficiency bonus adjustment element

charactersheet/charactersheet/templates/character/spells.tmpl.html
Set min to 0 for spell level for spell edit modal
Fixes #1157
=> Set min to 0 for spell level for spell edit modal

charactersheet/charactersheet/models/character/spell_slot.js, charactersheet/charactersheet/templates/character/spell_slots.tmpl.html, charactersheet/charactersheet/viewmodels/character/spell_slots.js, test/models/test_slots.js, test/viewmodels/test_spell_slots.js
* Changed initial modal focus to max slots in add/edit. 
* Somewhat fixed "auto-spell-slot-level-calculation."
* Removed default value from maxSlot, since it would always get overwritten anyway.
* Added short/long rest icons to spell slots.
Fixes #1106
=> Spell slots field focus

charactersheet/charactersheet/models/character/spell_slot.js, charactersheet/charactersheet/templates/character/spell_slots.tmpl.html, charactersheet/charactersheet/viewmodels/character/spell_slots.js, test/characters/jebeddo_data.js, test/viewmodels/test_spell_slots.js
Fix UI on Spell Slots to match Tracked Features
Includes:
* Add short/long rest icons
* Add sorting back
* Changed reset col to match tracked features
Fixes #1162
=> Fix UI on Spell Slots to match Tracked Features

charactersheet/charactersheet/models/common/treasure.js, test/models/test_treasure.js
Defaults to zero when parsing a currency results in NaN
* #1247 
* N/A
=> Convert blank values to zero when calculating gold. Fixes #1247

charactersheet/charactersheet/models/common/player_info.js, test/fixtures.js
Insecure resources can be blocked by browsers in secure settings. Removing the protocol means the browser will use whatever protocol it was served with.
None logged
None
None
=> Removes protocol method which could cause content from Gravatar to be blocked over HTTPS

charactersheet/charactersheet/models/common/character.js, charactersheet/charactersheet/models/common/chat_room.js, charactersheet/charactersheet/templates/common/party_manager.tmpl.html, charactersheet/charactersheet/viewmodels/common/chat/chat_detail.js, charactersheet/style/site.css
Room names are just the name now without the full jid.
Makes players names in chat window less subdued.
=> Party modal text fix

bower.json, charactersheet/charactersheet/index.html, charactersheet/charactersheet/settings.js, charactersheet/charactersheet/viewmodels/common/chat/chat_log_chat_item.js, package.json
- Adds [linkify](http://soapbox.github.io/linkifyjs/docs/) for parsing links, emails, and hashtags to html markup
- Links are truncated at 50 characters to prevent long links from displaying
- Only implemented in chat
Fixes #1423
=> Link detection

charactersheet/charactersheet/models/common/character.js, charactersheet/charactersheet/templates/dm/encounter_sections/environment_section.tmpl.html, charactersheet/charactersheet/utilities/convenience.js, charactersheet/charactersheet/viewmodels/common/player_image.js, charactersheet/charactersheet/viewmodels/dm/encounter_sections/environment_section.js
Added convenience method for converting dropbox links to direct images. Applied to character picker, environment section, and profile picture.
__Note__: The reason I run the link converter even before knowing if it's a dropbox link is because I simply do a `.replace()`, and if it doesn't have the criteria, it just returns the same input string, which shouldn't mess anything up.
Fixes #1407 
Fixes #1429
=> Dropbox image converter

charactersheet/charactersheet/templates/dm/party.tmpl.html
When no one is in the party but the DM, they now get a message explaining why the Dashboard is blank.
None logged
None
=> Adds placeholder for dashboard if no one is connected.

charactersheet/charactersheet/components/nested-list.js, charactersheet/charactersheet/templates/dm/encounter.tmpl.html, charactersheet/style/site.css
REMAKE AFTER CORRUPTED BRANCH
- Makes encounters detail bigger on larger devices
- Removes some spacing between master and detail views.
- Removes list outlines.
- Removes inner padding on master list. Items now fill the panel.
None logged
None
=> Remake of encounter-layout after botched branch creation

charactersheet/charactersheet/services/common/sync/card_service.js, charactersheet/charactersheet/viewmodels/character/character_root.js, charactersheet/charactersheet/viewmodels/common/party_manager.js, charactersheet/charactersheet/viewmodels/dm/dm_root.js
- The Character/DM card publishing services no longer keep their notifications active after switching characters.
- The party manager no longer re-shows the "Manage Party" link after switching characters unless the user is actually logged in.
None logged
=> Fixes issue with switching characters 

charactersheet/charactersheet/viewmodels/common/chat/chat_log_read_aloud_item.js, charactersheet/charactersheet/viewmodels/common/notes.js
- Fixes issue where notes are not saved when chat messages are saved. This could cause data loss in some cases.
- Fixes #1487
None
None
=> Fixes issue where notes do not save when switching notes.

charactersheet/charactersheet/viewmodels/character/exhibit.js
- Players pushing cards no longer affects the Player Exhibit Service.
Should fix #1491 as well
None
None
=> Fixes issue where any pushed party card would cause the exhibit to clear for most of the party

charactersheet/charactersheet/models/common/message.js, charactersheet/charactersheet/services/common/account/messaging/chat_service.js, charactersheet/charactersheet/services/common/account/messaging/node_service.js, charactersheet/charactersheet/services/common/account/xmpp_connection_service.js, charactersheet/charactersheet/utilities/notifications.js, charactersheet/charactersheet/viewmodels/character/character_root.js, charactersheet/charactersheet/viewmodels/common/chat/chat_detail.js, charactersheet/charactersheet/viewmodels/common/party_manager.js, charactersheet/charactersheet/viewmodels/dm/dm_root.js
- Once an inturruption is detected and the service has been disconnected,
the service attempts to restore the connection using a linear backoff retry
algorithm.
- During XMPP reconnect, the connection object is now recreated. This is
because of the fact that Strophe plugins do not handle reconnecting the same
object very well, and it's easier to just recreate it. This change leads to a number of issues which have been addressed. The biggest of these issues is that upon disconnect, all connection handlers are dumped by Strophe. This change means that once a reconnect event is detected, the handlers must be re-added. To address this:
- A new `initialized` notification is fired after the connection is created to allow view
models to re-add their desired handlers before the connection is …
=> Adds a new XMPP Websocket Connection Retry Cycle that actually works.

charactersheet/charactersheet/components/nested-list.js, charactersheet/style/site.css
Hit box for collapsing/uncollapsing nested encounters is now bigger to help with usability.
None
None
None
=> Increases encoutner collapse button hit-box size

charactersheet/charactersheet/viewmodels/character/stats.js
Issue was that health and hit dice model didn't exist right after creation, when the status line calculations would happen. Had the calculation fire again when they were loaded in.
Fixes #1490
=> Characters are no longer dead upon creation.

charactersheet/charactersheet/services/common/account/xmpp_connection_service.js
Adds new polling for XMPP Connections 
**Update**
> WebSocket Connections time out at 5 mins if no traffic. The previous timeout
ran the risk of operating directly on that limit. A 1 minute buffer should fix
that.
Fixes issue where XMPP Connections will timeout after long periods of idle.
None
None
=> Adds 4 minute XMPP ping to keep connection alive.

charactersheet/charactersheet/viewmodels/character/stats.js
Add death save success toastr
When 3 successes occur, a toastr msg is sent to the players
#1517
=> Add death save success toastr

.travis.yml, charactersheet/charactersheet/init.js, karma.conf.js, webpack.common.js
- The app boots again.
- Removes Isparta-Loader for now since it was messing up imports.
- Adds KO mapping ignore back to init. It was commented out for some reason.
**Note** we might want to [look at this new plugin instead of isparta](https://github.com/webpack-contrib/istanbul-instrumenter-loader#install) since isparta is deprecated.
None Logged
None
None
=> Removes Isparta-Loader for now since it was messing up imports.

.bowerrc
We don't need a `.bowerrc` anymore.
None
None
None
=> Removes legacy bower file.

src/charactersheet/components/nested-list.js, src/charactersheet/models/dm/encounter.js, src/charactersheet/viewmodels/dm/encounter/index.html, src/charactersheet/viewmodels/dm/encounter/index.js, src/charactersheet/viewmodels/dm/encounter_add_edit_modal/index.js, src/charactersheet/viewmodels/dm/encounter_cell/index.js, src/charactersheet/viewmodels/dm/encounter_detail/index.js, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/monster_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/notes_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/player_text_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/index.js, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/index.js
- An issue with Knockout Computed Observables caused too many mutations of the existing encounter which mapped the data improperly.
- Fixes an issue where multiple campaigns with the same encounters would conflict.
Fixes #1589 
None
None
=> Encounter Names and Locations Now Save

src/charactersheet/viewmodels/dm/encounter/index.js, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/index.js
- Fixes an issue that caused  errors in the console: Null selected encounter cells no longer attempts to set a non-null active encounter value.
- Fixes an issue with DM export failing.
Fixes #1614
Fixes #1618
None
None
=> Fixes issue with DM export and loading console error.

src/charactersheet/migrations/152_1_monster_ability_score.js, src/charactersheet/migrations/index.js, src/charactersheet/utilities/migrations.js, test/fixtures.js, test/migrations/index.js, test/migrations/test_migration_152_1_monster_ability_score.js
- Adds migration to remove old and unneeded ability scores generated by broken code.
- Adds tests.
Fixes #1552 
Related #1640 
None
None
=> Adds Migration to remove duplicate monster ability scores.

src/charactersheet/viewmodels/dm/encounter/index.js, src/charactersheet/viewmodels/dm/encounter_sections/notes_section/index.js
Removes an excessive notification that forces encounter sections to update.
None
None
None
=> Saving encounter with notes doesn't save a notes encounter section

src/charactersheet/viewmodels/common/wizard/steps/wizard_intro_step/index.html, src/charactersheet/viewmodels/common/wizard/steps/wizard_intro_step/index.js
- Disables import button in wizard unless there is a file selected.
- __SCOPE CREEP__: The app would import a character/campaign as soon as you selected them from dropbox, so even though a player cancels the import, the character/campaign was imported regardless. This issue has been addressed and now character/campaigns are only imported when the import button is pressed, as expected.
Fixes #1671
=> Disables import button in wizard unless there is a file selected.

src/charactersheet/viewmodels/common/characters/index.html, src/charactersheet/viewmodels/common/characters/index.js
- Deleting a character no longer causes a switch to the first character in the list, instead does not change the character unless the active one is being deleted. In this case it switches to the character at the same index post-delete (bounded by the total number of characters).
- Character switcher now also shows which character is selected using active CSS.
Fixes #1553 
None
=> Deleting a character no longer forces switch to first + UI tweaks.

src/charactersheet/utilities/character_manager.js, src/charactersheet/viewmodels/common/character_picker/index.js, src/charactersheet/viewmodels/common/root/index.js, src/charactersheet/viewmodels/common/wizard/index.js
**IMPORTANT: Looking for feedback on this. Not immediately for merge.**
- The Character Manager now uses the URL fragments as a store for the current character ID. This means that upon Application Load, we can first check the URL for an active character and load that instead of asking the user to choose.
- The AdventurersCodexViewModel is now aware of the new functions of the Character Manager.
- The Character Manager now has full documentation. 🎉🎉
```
/charactersheet/#c=233f2e75-ff33-48b6-b395-cee9f76cd669
```
Fixes #1600 
Characters/Games can now be bookmarked and saved by the user's browser, and refreshing the page no longer shoots the user back to the picker screen.
None
- 2017-12-04: Adds sample URL and emoji to PR notes.
=> Changes the Character Manager to save it's current character to the URL.

src/charactersheet/viewmodels/common/root/index.html
Adds padding back to player picture so that the inspiration doesn't look cut off at the top.
Fixes #1700
=> Fixes player/campaign image padding

src/charactersheet/services/common/account/xmpp_connection_service.js, src/charactersheet/utilities/character_manager.js, src/charactersheet/viewmodels/common/login/index.js, src/charactersheet/viewmodels/common/root/index.js
- XMPP Service no longer relies on CharacterManager notifications, instead using the more reliable User Service alerts which only fire on a correct and validated user being available to use.
- Character Manager now fires changed event on load if using ID from URL.
Other changes:
- Refactors login view model for asthetics and consistency.
None logged.
None
None
=> Fixes issue where refreshing saved character failed to init WSS connection.

src/charactersheet/viewmodels/dm/encounter_sections/environment_section/index.js
- Environment were only created if non-existent at component load. This is inaccurate. Now whenever the backing encounter changes, there is the opportunity to create a new environment if it doesnt exist.
Fixes #1725
=> Environment is created when loaded if none for the given encounter exist

src/charactersheet/models/common/spell.js, src/charactersheet/viewmodels/character/spells/index.html, src/charactersheet/viewmodels/character/spells/index.js, test/models/test_spell.js, test/viewmodels/test_spells.js
These are spells that are a) cantrips, b) prepared, c) always prepared. Updated displayed checkbox to display castable spells. Added save attribute to listing when the type of spell is saving throw.
Ability, especially for wizards, clerics, druids, and paladins, to filter out un-memorized entries during play.
=> Added ability to filter by currently castable spells.

src/charactersheet/utilities/fixtures.js, src/charactersheet/viewmodels/character/armor/index.html, src/charactersheet/viewmodels/character/armor/index.js, src/charactersheet/viewmodels/character/items/index.html, src/charactersheet/viewmodels/character/items/index.js, src/charactersheet/viewmodels/character/magic_items/index.html, src/charactersheet/viewmodels/character/magic_items/index.js, src/charactersheet/viewmodels/character/proficiencies/index.html, src/charactersheet/viewmodels/character/proficiencies/index.js, src/charactersheet/viewmodels/character/spells/index.html, src/charactersheet/viewmodels/character/spells/index.js, src/charactersheet/viewmodels/character/stats/index.html, src/charactersheet/viewmodels/character/stats/index.js, src/charactersheet/viewmodels/character/weapons/index.html, src/charactersheet/viewmodels/character/weapons/index.js, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/treasure_section/index.js, test/viewmodels/dm/test_treasure_section.js, test/viewmodels/test_armor.js, test/viewmodels/test_items.js, test/viewmodels/test_magic_items.js, test/viewmodels/test_proficiencies.js, test/viewmodels/test_spells.js, test/viewmodels/test_stats.js, test/viewmodels/test_weapons.js
Fixes persisting items when selected from an autocomplete dropdown. Fixes an issue where two elements required 2 downclicks to select an item in the weapons module. Fixes issue where spell save attr wouldn't show if Savings Throw was selected in the spell type field.
Fixes #1743 
Fixes #1741 
Fixes #1739
=> Autocomplete fix

src/charactersheet/models/character/health.js, src/charactersheet/viewmodels/character/stats/index.html, src/charactersheet/viewmodels/character/stats/index.js, test/viewmodels/test_stats.js
- damage plus-minus now uses a damage handler to subtract damage from temporary hit points before changing the stored damage.
- temporary hit points are reset on long rest.
=> Update damage bar to use a damageHandler

webpack.prod.js, webpack.test.js
- See other related changes here: https://github.com/adventurerscodex/configuration/pull/30
- XMPP now occurs over a web socket connection on a standard HTTP port under `/chat/` in both `nightly` and `prod`. This should help with connection issues caused by adblockers, VPNs and strict browser privacy settings.
None logged.
=> Changes Ejabberd URL to be on a standard port

src/charactersheet/viewmodels/character/stats/index.js
- Death Saves are automatically destroyed and recreated in cases where the data for them is corrupted.
=> Appliess a temporary fix for characters with damaged DeathSaves.

src/charactersheet/components/index.js, src/charactersheet/components/preview-edit.js, src/charactersheet/models/character/background.js, src/charactersheet/viewmodels/character/background/index.html, src/charactersheet/viewmodels/character/background/index.js, src/charactersheet/viewmodels/character/magic_items/index.html
Adds component to manage a preview and edit form.
- This implementation does not allow for autocomplete fields in the edit view. This functionality should still exist, but I was not able to think of a decent enough solution.
- A nice thing to have would be to put the edit/preview form in its own `.html` file. I tried to do that, but I wasn't able to inject it using the `template` binding due to scoping issues. This issue could be addressed by simply passing the template to the component, but this method was advised against by some.
=> Initial implementation of preview edit component.

src/charactersheet/services/common/persistence_service.js, src/charactersheet/viewmodels/common/characters/index.html, src/charactersheet/viewmodels/common/characters/index.js
- Persistence Service no longer uses localStorage. It has switched over to sessionStorage.
- The characters modal no longer shows the percent of local storage used.
=> Local Storage % removed from modal + PS uses sessionStorage now.

src/charactersheet/components/markdown-edit-preview.js, src/charactersheet/models/character/ability_score.js, src/charactersheet/models/character/skill.js, src/charactersheet/models/common/note.js, src/charactersheet/models/common/spell.js, src/charactersheet/models/common/wealth.js, src/charactersheet/models/common/weapon.js, src/charactersheet/services/character/sync/character_card_fields.js, src/charactersheet/services/common/sync/card_service.js, src/charactersheet/viewmodels/character/feats/index.js, src/charactersheet/viewmodels/character/features/index.js, src/charactersheet/viewmodels/character/magic_items/index.js, src/charactersheet/viewmodels/character/traits/index.js, src/charactersheet/viewmodels/character/wealth/index.html
- Added labels for currency denominations on Wealth section
- Fixes issue with feats and traits not refreshing after adding a new item.
- Removed setting of fake color when creating tracked.
- Fixed issue with magic items not subscribing to self when created.
- Fixes passive perception issue in character card field.
- Syncs up validation constraints between API and core.
- Updates ability score label in skills table to use short name.
- Updates markdown edit preview to make more sense.
=> Various bug fixes and improvements:

src/charactersheet/models/common/spell.js, src/charactersheet/viewmodels/character/spells/index.html
This field was required and shouldn't be.
=> Remove spell.damageType as a required field

src/charactersheet/services/common/account/authentication_service.js, src/charactersheet/services/common/index.js, webpack.dev.js, webpack.prod.js
There, on their accounts page, they can resend their registration email. This essentially prohibits un-registered users from using AC.
This should eliminate a lot of confusion around the current blank page that a user sees that tells them nothing about why they can't use the app.
None logged.
N/A
N/A
=> Users that are not registered are now redirected to their account profile

src/charactersheet/viewmodels/character/weapons/index.js
- Weapons now count quantity towards weight
- The ticket mentioned armor and magic items, but they have no quantity so they're already correct.
None logged.
N/A
N/A
=> Weapons now count quantity towards weight

src/charactersheet/components/index.js, src/charactersheet/components/named-fields-well/index.html, src/charactersheet/components/named-fields-well/index.js, src/charactersheet/models/dm/encounter_sections/trap.js, src/charactersheet/viewmodels/dm/encounter_sections/trap_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/trap_section/index.js, src/style/site.css
- Adds a new NamedFieldsWell component that can be used to conditionally
show/hide additional fields for a given model.
- Updates Trap UI to use the new component for a cleaner UI.
None logged.
None Logged
=> Updates Trap Encounter Section UI + Adds NamedFields Component

src/charactersheet/viewmodels/common/player_image/index.js
Previous checks only ensured the user was connected. Now we check both connection status and authentication status.
I've also moved the check of status above the await since this would cause lag in first detection.
None logged.
N/A
N/A
=> Ensure that the user only sees green connection status when both connected *and* authenticated

src/charactersheet/viewmodels/common/root/index.html
Hides share button for DM in order to release Character share first.
=> Hides the share button for DMs.

src/charactersheet/utilities/fixtures.js, src/charactersheet/viewmodels/character/stats/health.html, src/charactersheet/viewmodels/character/stats/health.js
Fixes issue where temp HP of greater value than Max HP caused the chart to overlap. Moves health color definition to Fixtures. Fixes tempHP blur.
=> Temp HP chart fix.

src/charactersheet/viewmodels/common/login/index.html, src/charactersheet/viewmodels/common/root/index.html
The navbar used to be kinda broken on small devices and would overflow onto two lines. This is fixed.
Also our navbar would collapse on small devices, but the dropdown would still exist. This essentially gave us two collapsed navbars, one inside of the other. This was very bad for UX. This is also fixed.
This commit also adds some accessibility features (titles for links).
I've also added more iconography to spice things up.
N/A
N/A
=> Fixes up Navbar display on small screens and cleans up code

src/charactersheet/models/dm/encounter_sections/point_of_interest.js, src/charactersheet/utilities/fixtures.js, src/charactersheet/viewmodels/character/wealth/view.html, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/index.html, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/index.js, src/style/site.css
These fields are optional and do not block submissions nor apply to old POIs.
This commit also adds some new flex utilities present in Bootstrap 4/5 but not in 3 and they're really nice.
This commit also redoes the Wealth Quick Spend to use these new utilities.
POI DC checks can be set to any text and number value, but the skill autopopulates the basic skills and stats.
This change requires the backend change merged as well.
Fixes #1551 
N/A
=> Adds new POI DC check fields.

package.json
Removes NoOp dependency.
From the console: 
```
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
```
N/A
N/A
N/A
=> This dependency does nothing and breaks our test builds

src/charactersheet/viewmodels/dm/encounter_sections/monster_section/view.html
There was a typo. Senses instead displayed skills. 
Fixes #2086 
N/A
N/A
=> Fixes typo that caused Monster Senses not to be displayed properly.

src/charactersheet/viewmodels/common/player_card/index.html, src/charactersheet/viewmodels/common/player_card/index.js
This commit ensures that cards are more readable by being the same height. This makes the cards much easier to glance at and read since they read row by row rather than jumping around.
This commit also exposes the underlying HP/Spell Slots/Trackables numbers to make it easier for the DM to gauge the actual values of their players.
None
None
=> Standardizes Card Layout + Adds Values for HP/Stats/Spells to Card.

src/charactersheet/viewmodels/common/player_card/index.html, src/charactersheet/viewmodels/common/player_card/index.js
[This commit](https://github.com/adventurerscodex/adventurerscodex/commit/2a489b3ed2d44accdc8ab1d17d1aacdac4eedb9f) broke the layout of player cards for players in a party when it tried to fix the layout for DMs. This has apparently been in master for some time.
This PR now fixes this issue.
None logged.
N/A
=> Fixes issue with player card fields showing for players when they shouldn't

src/charactersheet/services/dm/index.js, src/charactersheet/services/dm/weather.js, src/charactersheet/services/index.js, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/form.js
Adds a new button in the DM tools that sets the weather of the current environment to a random weather.
This change also introduces a new minor service function that allows for additional (currently unused) functionality.
The Weather in the generator comes from the items available on this page: https://donjon.bin.sh/d20/weather/ Though I have removed some and tweaked others.
N/A
N/A
=> Adds the ability for DMs to generate random weather for an encounter.

src/charactersheet/services/common/index.js, src/charactersheet/services/common/names.js, src/charactersheet/settings.js, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/form.html, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/form.js
This service is based on code from Donjon and uses a Markov Chain to generate realistic-ish names based on a list of sample names.
The seed data is pulled in via the DataRepository and this PR depends on that change.
This change only so far affects the NPC module of the DM tools as the New Character Wizard is under construction. This feature can be trivially added to that module at a later date to enable random PC names.
This change requires no API changes, only the Data Repository additions (other PR).
N/a
N/A
=> Adds new backend service for Random first/last Name Generation

Dockerfile
Docker build now uses package lock. It always should have but it didn't.
N/A
N/A
N/A
=> Adjusts the build to use the package lock

src/charactersheet/viewmodels/dm/root/index.js
Current version has a bug where DMs clicking the 'New' button in the toolbar does nothing because the app doesn't shut down correctly.
See above.
N/A
N/A
=> Fixes issue with DMs unable to click 'New' and see Wizard.

src/charactersheet/viewmodels/dm/initiative-tracker/index.html, src/charactersheet/viewmodels/dm/initiative-tracker/index.js
DMs can now exclude the automatic bonus calculation if they need to instead enter full initiative values rather than just dice rolls.
This allows the DM to set whether they'd prefer to enter dice rolls or full initiative.
N/A
N/A
=> Adds Bonuses Toggle to Initiative Tracker

src/charactersheet/viewmodels/character/items/index.js
This fixes containers whose own cost is not in GP causing the total value of all items to be calculated incorrectly - e.g. pouches, whose value is 5 SP, caused all their contained items to be summed up at 1/10 of their value.
BTW Since I cannot run the application locally, this is untested. It's such a small change that this shouldn't matter though. I would welcome a change to the setup that allows running it locally - otherwise you'll get very few PRs, especially for more complex bugs and features.
Edit: got it to run locally and tested this change, works as expected. Will also make a PR with the changes necessary to get it to run locally.
Has not been reported yet, I just fixed it directly ;)
-
-
=> Fix total item cost using a wrong calculated value for containers whose own cost is not in GP

src/charactersheet/models/dm/encounter_sections/npc.js, src/charactersheet/models/dm/encounter_sections/point_of_interest.js, src/charactersheet/viewmodels/dm/encounter_sections/environment_section/view.html, src/charactersheet/viewmodels/dm/encounter_sections/maps_and_images_section/view.html, src/charactersheet/viewmodels/dm/encounter_sections/npc_section/view.html, src/charactersheet/viewmodels/dm/encounter_sections/point_of_interest_section/view.html, src/style/site.css
This commit tweaks the DM sections UI to hide sections of the view cards if their data isn't present. Previously we showed placeholder text/images but that just takes up useful space and makes the cards hard to read on tablets.
N/A
N/A
=> DM UI Now Reflows based on Image/Text Presence.

src/charactersheet/components/form-submit-actions.js, src/charactersheet/utilities/index.js, src/charactersheet/utilities/upload_file.js, src/charactersheet/viewmodels/dm/encounter/import-form.html, src/charactersheet/viewmodels/dm/encounter/import-form.js, src/charactersheet/viewmodels/dm/encounter/index.js, src/charactersheet/viewmodels/dm/encounter/view.html, src/charactersheet/viewmodels/dm/encounter/view.js, src/charactersheet/viewmodels/dm/encounter_sections/trap_section/index.js, src/style/site.css
Allows DMs to create full encounters using the export files generated by donjon.bin.sh. 
Patrons with image upload slots available are allowed to upload map images also exported by Donjon to their encounter. The image is uploaded once and bound to several sub-encounters as the environment image.
List of resources imported:
- Wandering Monsters
- Rooms
- Doors
- Treasure
- Monsters
- Read-aloud Text
- Environment Descriptions
N/A
N/A
=> Adds support for uploading Donjon export files to create encounters.

src/charactersheet/viewmodels/character/skills/addForm.js
Fixes an issue (reported via Reddit DM) that the Skills section add form didn't refresh properly when adding data so adding multiple skills required a page reload.
From the report: 
> ...you cannot add multiple skills into the skill area without refreshing the page between each skill you add.
None
None
=> Fixes a reported bug where skills addForm didn't clear properly

src/charactersheet/viewmodels/common/notes/form.html, src/charactersheet/viewmodels/common/notes/form.js
We got a feature request to implement confirmation on deleting a note. 
None logged
N/A
=> Deleting a note now requires confirmation through a browser confrmation dialog box

src/charactersheet/viewmodels/dm/dm_portrait/view.html, src/style/site.css
Fixed bug introduced by adding a border to the profile image
NA
NA
=> Fixes image rings on profiles.

src/charactersheet/models/dm/campaign.js, src/charactersheet/utilities/fixtures.js, src/charactersheet/viewmodels/common/wizard/index.html, src/charactersheet/viewmodels/common/wizard/index.js, src/charactersheet/viewmodels/dm/dm_portrait/form.html, src/charactersheet/viewmodels/dm/dm_portrait/view.html
Adds fields to Camping (and DM Wizard) to better allow DMs to specify the time…/place/and theme of their games (and to provide overarching info when prompting GPT for suggestions.
These fields have two goals:
1. To provide a place for the DM to specify the setting of their campaign and also to provide a place for them to denote the themes. 
2. We can use these fields for suggestions (GPT or otherwise via pre-pop).
**Reminder** there is an API change needed for this.
N/A
N/A
=> Adds new Fields to a Campaign
